{
 "title": "chrony-exporter",
 "description": "Dashboard for Prometheus chrony_exporter",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values(chrony_up,instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Tracking",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Reference Source Name",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "chrony_tracking_info{instance=\"$instance\"}",
     "legendFormat": "{{ tracking_name }}"
    }
   ]
  },
  {
   "title": "Stratum",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "chrony_tracking_stratum{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Offset",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "chrony_tracking_last_offset_seconds{instance=\"$instance\"}",
     "legendFormat": "Last Offset"
    },
    {
     "expr": "chrony_tracking_rms_offset_seconds{instance=\"$instance\"}",
     "legendFormat": "RMS Offset (long term average)"
    },
    {
     "expr": "chrony_tracking_system_time_seconds{instance=\"$instance\"}",
     "legendFormat": "System Time"
    }
   ]
  },
  {
   "title": "Reference Source ID",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "chrony_tracking_info{instance=\"$instance\"}",
     "legendFormat": "{{ tracking_refid }}"
    }
   ]
  },
  {
   "title": "Maximum Clock Error",
   "type": "timeseries",
   "description": "Absolute bound on the computer’s clock accuracy (assuming the stratum-1 computer is correct)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "instance:chrony_clock_error_seconds:abs{instance=\"$instance\"}",
     "legendFormat": "Clock Error"
    }
   ]
  },
  {
   "title": "Source delay",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "chrony_tracking_root_delay_seconds{instance=\"$instance\"}",
     "legendFormat": "Root delay"
    },
    {
     "expr": "chrony_tracking_root_dispersion_seconds{instance=\"$instance\"}",
     "legendFormat": "Root dispersion"
    }
   ]
  },
  {
   "title": "Sources",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Current Status",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "chrony_sources_state_info{instance=\"$instance\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "chrony_sources_stratum{instance=\"$instance\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "chrony_sources_polling_interval_seconds{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Last Sample: Age",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "chrony_sources_last_sample_age_seconds{instance=\"$instance\"}",
     "legendFormat": "{{ source_address }} ({{ source_name }})"
    }
   ]
  },
  {
   "title": "Last Sample: Offset",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "chrony_sources_last_sample_offset_seconds{instance=\"$instance\"}",
     "legendFormat": "{{ source_address }} ({{ source_name }})"
    }
   ]
  },
  {
   "title": "Last Sample: Error Margin",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "chrony_sources_last_sample_error_margin_seconds{instance=\"$instance\"}",
     "legendFormat": "{{ source_address }} ({{ source_name }})"
    }
   ]
  }
 ]
}