apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lidarr-config
  namespace: lidarr
  labels:
    app.kubernetes.io/name: lidarr
    app.kubernetes.io/component: storage
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ${STORAGE_CLASS}
  resources:
    requests:
      storage: 5Gi
