apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: librespeed
  namespace: librespeed
  annotations:
    gethomepage.dev/enabled: "true"
    gethomepage.dev/href: "https://speed-apps.${CLUSTER_DOMAIN}"
    gethomepage.dev/group: Platform
    gethomepage.dev/name: LibreSpeed
    gethomepage.dev/icon: librespeed.png
    gethomepage.dev/description: Network speed test
spec:
  parentRefs:
    - name: envoy-gateway
      namespace: kube-system
  hostnames:
    - "speed-apps.${CLUSTER_DOMAIN}"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: librespeed
          port: 80
