apiVersion: ENC[AES256_GCM,data:ffc=,iv:OxxozIamD8KWOXumJ0LtsGWekzTtMYP3/GdeCy4/rQ4=,tag:hyhZteHRErHrVYAx+T5M7Q==,type:str]
kind: ENC[AES256_GCM,data:2Gb3t8mz,iv:bV4AOkdJRa8OzppQdgcJSlUp0UT9IsW7TxTBHdk5blY=,tag:quisu5rAOXPQCN9JYmHJIA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:j4nVrzTrtQLzp7Lzj4MacQ==,iv:Sb2NgIXoDnumxQXi+RXPpmXQ4k1qG2E8BuwjwOahnvo=,tag:KA/34+nr6LIyKFKSWV3DXw==,type:str]
    namespace: ENC[AES256_GCM,data:n9duAFwlQd7h,iv:hbslycUcNUkLNcIKOzEP6IalwPJMHtXomvI0Zoq9hRc=,tag:Hs8/5ifZD4hXc+dEghK7nA==,type:str]
    labels:
        app.kubernetes.io/name: ENC[AES256_GCM,data:YFnkzwArBPsi,iv:Ifm0wmWitKzH8/6F4T60kTL8hoJXvOEck6dVfVcC33E=,tag:Nz8Iud0feEnkmH/EMsp+cg==,type:str]
        app.kubernetes.io/component: ENC[AES256_GCM,data:dD1JeQ==,iv:p8qBlnBI4jTott2CtNRvIe2ih38mu39kmVIkwXhXJdo=,tag:wHqo+He1WYEgcIhYYSQMXg==,type:str]
type: ENC[AES256_GCM,data:qy5AYRRn,iv:nvXf2lVgIqyfHy1iMjWhld+0JSRYkLIRSLCrkZLC0Gc=,tag:HcFuV/pjFmMFxeIATrZShQ==,type:str]
stringData:
    passwd: ENC[AES256_GCM,data:sIyRANRwv2UfYopxkjBsAHRdtUqT16zkmNEBPT9zYeXD2EJDeKGqm+Phgm8nDNDb9Rkro8twdjmyaYcFRk03dBFVso7/07c0X43CNqOoaHRUVoXtItM6LTCFWpkx+qEJxxp4LcuoqsEEV/L4bfh52583Ji8N1BM=,iv:mcvJq4us98Q+YveCR+q9hFOFhrk5L6ZULN4RQd4Hh9w=,tag:mjnyEA4KEcYnRbFgOjuN8Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXTmpybFdqMlpEZ2doR0pE
            WStsZm9iQ3FtakxNQUsxWHRZbWl1RU02cUY0CldRZlBuaEx4OGM0NnQrOWttN0xG
            UjdhTnFJZUc2bzk1WDV1Mk1ralJyeUEKLS0tIHM3dFpQMUZGck9NMGNPbVRBUTlx
            NnprRjQ4bThyS0djSDVhMitSR0g5TjgKww0lMswHfSQ5CLSrQAZy5wkGCGZHvgPV
            /nTixKHv5zgxTV8VVkPPbKCg9M1hkkOErqYqvAwkNyH3Q+PtPxFfDA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1j6zlq24dlzd9as6gq835980ahzelmnuu7d8ydkz54t28kzhv0csse96epz
    lastmodified: "2026-07-20T18:25:35Z"
    mac: ENC[AES256_GCM,data:WL605ZrrB+ozDZW0VqcHu6zVftq09aAJ/zI2ZrM6c202jyZauuqar6oso5rpl0EBooi45iu0pm1WNdyGv9YZ6w+hM6RBRDB0jbaaN3RCNx0dIi7I7tTgJT9tGf45yssdnoAj827Rp9ZfTLd06XCEvpDeIf35Gt/vtm1q+/79Hss=,iv:5s/u3VNCpwmOHLsjErWXCNrab0zkQDXiiiH4xQClhz8=,tag:FW7dzpfmGhagdxVBXSfcfQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
