apiVersion: ENC[AES256_GCM,data:ffc=,iv:OxxozIamD8KWOXumJ0LtsGWekzTtMYP3/GdeCy4/rQ4=,tag:hyhZteHRErHrVYAx+T5M7Q==,type:str]
kind: ENC[AES256_GCM,data:2Gb3t8mz,iv:bV4AOkdJRa8OzppQdgcJSlUp0UT9IsW7TxTBHdk5blY=,tag:quisu5rAOXPQCN9JYmHJIA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:j4nVrzTrtQLzp7Lzj4MacQ==,iv:Sb2NgIXoDnumxQXi+RXPpmXQ4k1qG2E8BuwjwOahnvo=,tag:KA/34+nr6LIyKFKSWV3DXw==,type:str]
    namespace: ENC[AES256_GCM,data:n9duAFwlQd7h,iv:hbslycUcNUkLNcIKOzEP6IalwPJMHtXomvI0Zoq9hRc=,tag:Hs8/5ifZD4hXc+dEghK7nA==,type:str]
    labels:
        app.kubernetes.io/name: ENC[AES256_GCM,data:YFnkzwArBPsi,iv:Ifm0wmWitKzH8/6F4T60kTL8hoJXvOEck6dVfVcC33E=,tag:Nz8Iud0feEnkmH/EMsp+cg==,type:str]
        app.kubernetes.io/component: ENC[AES256_GCM,data:dD1JeQ==,iv:p8qBlnBI4jTott2CtNRvIe2ih38mu39kmVIkwXhXJdo=,tag:wHqo+He1WYEgcIhYYSQMXg==,type:str]
type: ENC[AES256_GCM,data:qy5AYRRn,iv:nvXf2lVgIqyfHy1iMjWhld+0JSRYkLIRSLCrkZLC0Gc=,tag:HcFuV/pjFmMFxeIATrZShQ==,type:str]
stringData:
    passwd: ENC[AES256_GCM,data:rqPU94l7jJyQ35/WHtVGO1KlpwpqRGDxyn60Q6ICXotfWmGzu9X5SmQghlk+9PCXd7j4bT3WbEbUCnSK3xzgpebPpDOcdy8agCpdDV7n7Sohm1YW7M8+3nzv6Iw7htaNnORyTzlZBsMvgr8CS7MrOr2RpqrEU6DsjWzJciQxUkG+ThGZrmkYbWjHbBR9jZMnVTtaj3TJD24gea8bUKx3R/9Vu9BdhpF8RuJAxlGBc+ghRuGp4pjd+YIVwnB3rF8=,iv:PSGA912NYuaT4KQzhRQte/mZHvvORhako4ojAbIMnJk=,tag:XbuLrXwSVlcbhvmboisq0w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXTmpybFdqMlpEZ2doR0pE
            WStsZm9iQ3FtakxNQUsxWHRZbWl1RU02cUY0CldRZlBuaEx4OGM0NnQrOWttN0xG
            UjdhTnFJZUc2bzk1WDV1Mk1ralJyeUEKLS0tIHM3dFpQMUZGck9NMGNPbVRBUTlx
            NnprRjQ4bThyS0djSDVhMitSR0g5TjgKww0lMswHfSQ5CLSrQAZy5wkGCGZHvgPV
            /nTixKHv5zgxTV8VVkPPbKCg9M1hkkOErqYqvAwkNyH3Q+PtPxFfDA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1j6zlq24dlzd9as6gq835980ahzelmnuu7d8ydkz54t28kzhv0csse96epz
    lastmodified: "2026-07-21T11:32:50Z"
    mac: ENC[AES256_GCM,data:+4KyiBScPFCbgGBcBIIVeGTM8AfS/WqqV4h3mObS6+b4wAhoVFjSy5QjKsDlqbg5PcUb5A8hHZ+3iMg8LHgxtNsiynHL9g6AaKkRFVD55mygqOKpxj47ujsLJTUi+1Rim2iR7zVFk96dK6Ea71+p1myTRYSL9t9eWBNXfdkPBs0=,iv:xFlv/ywHcQtw5NqCuqeu6xF60ooK4bP39Lh5m9Zctdg=,tag:o3mqnNApkt5tu1RKKrwi7g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
