apiVersion: ENC[AES256_GCM,data:ZE0=,iv:IVnkikHpVStSAbdeiYJpPb3yH1Cjn4tIVchD0nrAVlU=,tag:1HOAUSvGTRD5DOuVbEOSXA==,type:str]
kind: ENC[AES256_GCM,data:rhQ4qGkO,iv:weGaihkGa/9CAKaYZbw6bFjqUN+ffJoxxjE18HehiI0=,tag:6WPGWvTqOXribIgKRg5Fyw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:M8mdP4vJjCTEaIWz5fU03bxg9r4W,iv:xYBH/104fb906GAI70ito8MpgE39PXheVjtcFDmqyhk=,tag:nXuR9Uv3MVVKbvvoPEChzA==,type:str]
    namespace: ENC[AES256_GCM,data:VCalkFjXIOM=,iv:/HLzj8B1yObeoMiAwlNBKlr98OyF4+VaDK4lpNmQCwg=,tag:upAHPjf0ABODF1SdTFZ/Kw==,type:str]
type: ENC[AES256_GCM,data:pjH7WXRs,iv:/eVAiYt1shiPuNhsWj3qQWfaWKkIS072BzXZ85n10mc=,tag:G2w8z0qIZ6gVsbaEcgaPVQ==,type:str]
stringData:
    RENOVATE_TOKEN: ENC[AES256_GCM,data:58HTWBwP12A6x2Ie9nkMJivrLBmKLVc=,iv:xLKzL5aZRyNtvDoM4JyT5qmbclaoWqyihhd5pzQkDlQ=,tag:uG3Amu9qaYaPyLyz84E1SA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuOTNVTW9LcTJQS1laeXVN
            R0VySnRwc2NQRHdOYnNCMlVrTWtMUG5YWEFJCkkrTGY2WHgyOHJWZlBOSHpXSXhw
            eXBTMWtJUlZPQXcvNmtsN24vam02VU0KLS0tIGZ4UVZIRXhveXhMUjgreG5RZ2kw
            ZnpnWHlWTGNkaTk5ZGdnS1czRjdEeFkKURl3E6b1LszLZ9RJ/uO/wxLoesVmExoR
            vYb13yaflfYdWhXlSWTBhFNYMHQ0qbEI7IMuMN+Ft4e4sAaG0gtsig==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1j6zlq24dlzd9as6gq835980ahzelmnuu7d8ydkz54t28kzhv0csse96epz
    lastmodified: "2026-07-25T22:53:38Z"
    mac: ENC[AES256_GCM,data:IXih1G6xx3rBJx2UL5DHzckqzAjq+Y5d3jQ4eHTuLaY9+ktqcL0swoheHDnRbsVphQWZQu0JzYSY2M1Qy2SzgqxscZuEy3LR9tQCit1Sn4TrTK42gpjwqd/9QcBZFGHg+XhpOODnypZ6QStTXZWT69mhmR7Fmbe9xvPLbNQP6/g=,iv:eucM+QLKi38hUAgB7jcHgC7nY6VBYVJiQKuqBl39caM=,tag:9FwY0DR1eJOSEHahMAElWw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
