apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: authelia-httproute-grant
  namespace: authelia
spec:
  from:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      namespace: longhorn-system
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      namespace: headlamp
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      namespace: esphome
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      namespace: zigbee2mqtt
  to:
    - group: ""
      kind: Service
      name: authelia
