apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authelia
  namespace: authelia
spec:
  interval: 30m
  chart:
    spec:
      chart: authelia
      version: "0.9.*"
      sourceRef:
        kind: HelmRepository
        name: authelia
        namespace: flux-system
      interval: 12h
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    secret:
      existingSecret: authelia-secret
    pod:
      kind: Deployment
      replicas: 1
      strategy:
        type: Recreate
      extraVolumes:
        - name: authelia-users
          secret:
            secretName: authelia-secret
      extraVolumeMounts:
        - name: authelia-users
          mountPath: /config/users_database.yml
          subPath: users_database.yml
          readOnly: true
    configMap:
      theme: dark
      server:
        host: 0.0.0.0
        port: 9091
        buffers:
          authz:
            read: 8192
            write: 8192
        endpoints:
          authz:
            ext-authz:
              implementation: ExtAuthz
              authn_strategies:
                - name: HeaderAuthorization
                  schemes:
                    - Basic
                    - Bearer
                - name: CookieSession
      log:
        level: info
      default_2fa_method: totp
      authentication_backend:
        file:
          enabled: true
          path: /config/users_database.yml
      access_control:
        default_policy: two_factor
        rules:
          - domain:
              - "longhorn-adm.homme.ar"
            policy: one_factor
          - domain:
              - "*.homme.ar"
            policy: two_factor
      session:
        name: authelia_session
        cookies:
          - domain: homme.ar
            subdomain: auth
            authelia_url: https://auth.homme.ar
            name: authelia_session
      storage:
        local:
          enabled: true
          path: /config/db.sqlite3
      notifier:
        filesystem:
          enabled: true
          filename: /config/notification.txt
    persistence:
      enabled: true
      storageClass: longhorn
      accessMode: ReadWriteOnce
      size: 1Gi
    service:
      port: 80
