apiVersion: ENC[AES256_GCM,data:vBY=,iv:gJMr4e1MrejK56DNJO8a6Jns+FVwGC7OkYRQjmpAi4o=,tag:BbJP5ctcIC6Cz789X9V+Bw==,type:str]
kind: ENC[AES256_GCM,data:jdk25jLe,iv:0OB6Q+7S3xdSieHzwwJU0JayDqvzdRB2D4reCcy8EDw=,tag:DxNQvqy3u/k5/p6zuQfe9w==,type:str]
metadata:
    name: ENC[AES256_GCM,data:J6mMafiGxXmbe/IGU8lv,iv:RLiWqaeuAJL9HZE9kmlVgIMQNRaIpPjtEkQ3OTkxbHw=,tag:MssyJyz0eDILgxPn/nopAw==,type:str]
    namespace: ENC[AES256_GCM,data:KnNWpRZdYIs=,iv:2aO870kaitMfYdTsz/wAH3dkd9o0XOntpaj4xVTNk+g=,tag:OvymsiM/X/TBi/onoGUllA==,type:str]
type: ENC[AES256_GCM,data:GunMlZiM,iv:FfN8ZEjxR6NhtABaI/ZpB9ZihuAhWqV96aoDH9jQ4YA=,tag:gIB9Oubk0K/knhdtTxyWfQ==,type:str]
stringData:
    jwt_secret: ENC[AES256_GCM,data:tR4bsgf5hxd/BnbRHYamAKMTOpMPH1zvSEQr2u7Yoxs=,iv:yOADfUHzthsx6D6PJ8lBVgijhLS3CzYQjCYfZpL6L64=,tag:UH6GFuW9foY050M2W5enMQ==,type:str]
    jwt.secret: ENC[AES256_GCM,data:d3PMkMfH0TocP/X7ZPM29N3PUcjEjIOiiyVCO9287U0=,iv:5peMi2AQERknIBVTq4HvgdtnrKUFu8W+pUZ7DVAsbWs=,tag:JhJjPXpVmGeZD8TzIUWExQ==,type:str]
    jwt.encryption.key: ENC[AES256_GCM,data:ZvyJQBIR9Eoy9tFCXTKIL18JYBvW3hZadSsPnVMD4xU=,iv:Na8tRPja94COM9k9h+iZMhGK5DlzS0/H0YEzw4jRGmU=,tag:7koifTa4hmTwI16imaSsdw==,type:str]
    identity_validation.reset_password.jwt.hmac.key: ENC[AES256_GCM,data:+p7dvEHc3WwaTpoq0oyZGygq1cuaQJJJe3R1afD5jWY=,iv:x3aHnoOXemwjoCD91nbBOjkYYYOw8DK/uf/4fxv4E4M=,tag:MuF2L0zHc4+0UnQIj/J33A==,type:str]
    session_secret: ENC[AES256_GCM,data:9jd8LGv8pLyvcqVkWFLdkPSUXcZQ622mb63HK7VkPsU=,iv:f7RtHDGVcCKL1tzvO7KNmODUS7yFvPqcRbeTT0USuVI=,tag:DLyx3RSOvtMtbX3L1I5lgA==,type:str]
    session.secret: ENC[AES256_GCM,data:Au870U/fPDuOb435L6UqyWScsas7Gbr62aBwnaubq94=,iv:puhJN17yWsL+ykTmQUZ8XdP0A/BACL2u2LMHQtd+/DE=,tag:aipuJAgwQgTPLxdjnh5j6Q==,type:str]
    session.encryption_key: ENC[AES256_GCM,data:bERqi399le7w0S0F1LmpGAIF8Rf94m0i7zO1Im5a/IY=,iv:mKBFF9p34ZaDjhTQGSsdWtZ+Z2z+Vw9/LysjJqdonQk=,tag:bwGImsG5KeGLnRnRlfNGXQ==,type:str]
    session.encryption.key: ENC[AES256_GCM,data:PUniQPEj99uE1DB+5DZdlMyztYiblSxHhxf72V5C66w=,iv:jHnXWP5iINAgWKf/G1/KLugEojWsfnnrAq3BMMK/QVI=,tag:AjU0tNs6jG2uaTpNkU2VSQ==,type:str]
    storage_encryption_key: ENC[AES256_GCM,data:Ybk2TaLpYzczR5YwKq49mG4DsRbNUodPMLL9bPKblEs=,iv:vO7YFLCCSiT+T60SENH7XyNzCoMQtcdMZywujm1vcxw=,tag:UXUut8KMzXaJrSjtr3iIWw==,type:str]
    storage.encryption_key: ENC[AES256_GCM,data:BD/lhsD5Pl5HKSBEuXB35s3nsAebze8hQI9OSldAnAA=,iv:ujFAm+xzkJP93NX1fPeY9r+jHaQJJBRPk4fm9OSupqk=,tag:1SD8Eg1rjDgLR5TA7FKqAg==,type:str]
    storage.encryption.key: ENC[AES256_GCM,data:+9Ij3ndEmg77ngNY6TNgH/dUj3EReyALFOjmBlqNglA=,iv:dDZ5y4VXB2fo9Ip+zDMXwCB6xThJJWI98NkMQTS4PUw=,tag:nSNy+MgT25pAbeDMdwiNfw==,type:str]
    users_database.yml: ENC[AES256_GCM,data:rYM/pS2SGu3uVf2A1S+l4A8kgHmhjkfxpnb+x7ioTbXLqTyY2f2nTRaaZ8aXXVIaL4tC+Nai/tH+LmxxwaswI+QRAb8gkIRJIN1CS/shYl9G1bAf936SVpyaUSsWr69vVB2hwJ00YdyFcK6NRBtybi2mVUBNCr+/ktZSyi9ysb7DM1oeEoXw2Q0mrfV8ug/IzsZXmgmbWUW6sTMK3QdrI94v75w4Fr/zfopPZBzOK9CeOGdjV75n0vwrzKu8A89JdPQdKG3BfNkfSwKueYM8zvBau4vVGBSFx94AqJ+DC/jIaXLjrqX0LafW0O4yCsjaNeBAvWU90owSaDE=,iv:S4oXTphD4swxQNLSafWljAI+VMiOOkIwoHNqheQ/wz4=,tag:JxjVhIPjWFvl8XUPN3u7tQ==,type:str]
    storage.postgres.password: ENC[AES256_GCM,data:AsS3j/ee8i/+M0RYVGdiVzXuo5F9RiiGDoVDuf5bm2U=,iv:mla+g1lISQaSrb0a7yUtZgizvsXxwpGfI/ga2aXRQ1A=,tag:OcCZhDmAO2UbVP6yLsPaMQ==,type:str]
    notifier.smtp.password: ENC[AES256_GCM,data:eryheOGofdPosnQMxRvilj+R0cE=,iv:O1mtFNZbDVbNOFw7KN7+geg0fuRu0hhVCHusoVxtL/s=,tag:JDrs1SOVqwbXEQYVDlzNRw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFS3Z0akFaSlJlNk0wOWhL
            ZjRVRTI0am14QjlaQlJBbTYwZ0pMWnRaSWxVCnNWT2RlZFdmK1RORGpGdTlKMmlF
            NHJFeVZ1WFA0dlBtNmsxNGV0OUROS2MKLS0tIGFWWmRxZG50UVd0YUQ0R3ZRMGo5
            S3U3c21zQkZIWjA0ZnRyVStFa21RbzQKloSjgvy32V7olyyHLNN8Eez+1/2J7+Ku
            SR+fIoRX7zgG2l+t3PPs6c+wC/V8uzAm0NPLwDwiQuOQkuX0I1vflQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1j6zlq24dlzd9as6gq835980ahzelmnuu7d8ydkz54t28kzhv0csse96epz
    lastmodified: "2026-07-20T02:45:28Z"
    mac: ENC[AES256_GCM,data:JgVPbj0gsaaWU/T/JHrHoIFh1WCyWItc8kzrKSz2fIAhzwsfrtcsu2aco6hZXSsjJExGqKHMo/mHT1VTYhSHb5WrJeVBQvVZ1jh7bxWRq0rU9sPdh2RJkjlnIrouChSs1OhERX5Zirl3hEsOLVVNT/B75AnFLsR+tMKiSSY+3N0=,iv:vcdqcaP6Pn72EQka5omHPCKW3Ob6z89VeahakeIAo6k=,tag:INh1rRpQ7n9SVY33RksJxw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
