apiVersion: v1
kind: Secret
metadata:
    name: jellyfin-metadata-refresh
    namespace: jellyfin
stringData:
    JELLYFIN_API_KEY: ENC[AES256_GCM,data:s7Wz/iibO+SjKIq0lx5MVn85C1kZoqShM/IWsIXiV2M=,iv:9/rHuQdQw2x+6szYlGJA202e/CCSxAE0zln+3uxnzF8=,tag:SCta6luYyhmD8D/xLR6kyg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3ZldPeTE3ckxIOWcrTFJs
            RGRTN3FTRVpneG1jTU56UDRmdGdtdE9qTzNzCnQ1VXhmcngxczVDcnBPcEExTHJR
            VjIwYm9TS1JKb1hESUZNdk5kVWtBVk0KLS0tIDBKNStUUDNyS2h4ZjlvY0FYRmZn
            K09vaCtLb0VEbEl1djhEWmVVNDRuNHMKaPTrbhPrNJa/XFXw5oija2FguRdUtiPy
            1nUSdTaOL+wkksOd/V7ooHsNbEFD1TiMCZEM6PJyTijPdMS7kcIScQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1j6zlq24dlzd9as6gq835980ahzelmnuu7d8ydkz54t28kzhv0csse96epz
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-30T04:22:13Z"
    mac: ENC[AES256_GCM,data:8UOuDAgubrimaLKU4hmRryW5cjbBDEGVKNjSUuadZDaV52PamcPTrc0CdFt9Gpl1hq0eGQvNN2G4lRiQYUFnFh/eGsZgkW71AVeJmYfKFhCn5fgvpreNCtBJ4C9yeCHlB6gUjhuFiPh4fiP1NhHdLyAYnqQU34G3TwptZP6uUrw=,iv:zmVR/OnjiMA/1OcsLtXfHDA4xHi/ElYzHFyG5dq2PSY=,tag:QboaliVYCVu1CJdgcDRwYw==,type:str]
    version: 3.13.2
