apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nas-media
  namespace: jellyfin
  labels:
    app.kubernetes.io/name: jellyfin
    app.kubernetes.io/component: storage
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: jellyfin-nas
  resources:
    requests:
      storage: 1Pi
