apiVersion: v1
kind: Secret
metadata:
    name: lingarr-secret
    namespace: lingarr
type: Opaque
stringData:
    RADARR_API_KEY: ENC[AES256_GCM,data:kjn1bX/hpDp7,iv:ywGE009ttbtOKb2lqFkKNVOs+DHqg9vs6GQuQ6F+sRQ=,tag:zKss3oDMsEFTt3BtiYp6NQ==,type:str]
    SONARR_API_KEY: ENC[AES256_GCM,data:rG0r9spd2Yp/,iv:ILGxRHTT7uaqtDDGs8COoN/K831xRSn36WBncYVBRg0=,tag:MKGUDGrhFy54TS1ufXgx4A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1dE52NGdlZldPZ0NFUGF2
            WHlYMWZTRmkvSHpyMG1TNE9uZ3dUT2djank4ClFOWWU5RDN1bTdiM29DSW9Jb0lX
            OWw5V2cwRGdRdml5RUV5OTFhRWg0aVUKLS0tIHliNGlZNU42SmxEa1BlZUZLK0FK
            WmtoVlNKUUIxRUpGaDdUV3dZdUc4VEEKsEpkLBJMFy4JRLgZ/6ckgmJ3jJsc77n5
            yOKgB36wT0xz5UHKIPLQP/z5oE1o9/UopfEmXGX267UGMDPlC+a+5g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1j6zlq24dlzd9as6gq835980ahzelmnuu7d8ydkz54t28kzhv0csse96epz
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-04T02:02:04Z"
    mac: ENC[AES256_GCM,data:mgTXU1han6Wzxin2SHKrjVna7mzpddGVoO8681T7zLjycjbxdxVqZxr5ys0PKG9UlCyTCIG7I/4xeZwz8zUIADJH7fxd08gaINLqHpaSlFK63u3Z6h27iLtnRw9aZWY+oLfQUwXyT+HzHbl8dTYBj3KOlrohkKVz5uQC4DbDS54=,iv:AsIHWMQXOHZPY21KVBSOEkYzcjjD31KstQnh3opIhSM=,tag:H67I6aL92VMD/B/mB77c+A==,type:str]
    version: 3.13.2
