apiVersion: v1
kind: Secret
metadata:
    name: lingarr-secret
    namespace: lingarr
type: Opaque
stringData:
    SONARR_API_KEY: ENC[AES256_GCM,data:NiHDrr4MNPO99wwxk+VOduI32LHbuLjIUmmjpYpJKJA=,iv:h1seN+xAJP2wV2xTZ3dmxdWCgPhscLTPM53ugEGpgyE=,tag:INVY3CH3fUybNOZEWqnpvA==,type:str]
    RADARR_API_KEY: ENC[AES256_GCM,data:M5xveDT1Lp8Y66OOezlsaG2I0hISMEqebU8HDb9iBkU=,iv:+nvAAqVykLOrPixjXWHinwnlWPS1Ixw6+5zobUyaZ3U=,tag:DnzS8+7JiEaXefpm5fMH3A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1dE52NGdlZldPZ0NFUGF2
            WHlYMWZTRmkvSHpyMG1TNE9uZ3dUT2djank4ClFOWWU5RDN1bTdiM29DSW9Jb0lX
            OWw5V2cwRGdRdml5RUV5OTFhRWg0aVUKLS0tIHliNGlZNU42SmxEa1BlZUZLK0FK
            WmtoVlNKUUIxRUpGaDdUV3dZdUc4VEEKsEpkLBJMFy4JRLgZ/6ckgmJ3jJsc77n5
            yOKgB36wT0xz5UHKIPLQP/z5oE1o9/UopfEmXGX267UGMDPlC+a+5g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1j6zlq24dlzd9as6gq835980ahzelmnuu7d8ydkz54t28kzhv0csse96epz
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-04T02:29:37Z"
    mac: ENC[AES256_GCM,data:UJF1enigiTHJ/jLcQxcj2PfCy6EvqKrk1EZFLx70jwIylhE6/M+D9AbDXgHwB2gps5sjcdWAn40QBBrPoPGtkiGL1XFSCyZU5oGTnDBxLc5HzjPUF4x474kfiQA6InwjMPThM743CnNw5yDcegqNT9q2+ZoDkv0PT51sUhVtt+M=,iv:xEHW3vnauykmpVsQ6Cw0cFwdF+/oyvz3Gb2z+0iRFGA=,tag:wHoG1oYaqH+R4EWSzieqZw==,type:str]
    version: 3.13.2
