apiVersion: ENC[AES256_GCM,data:i1g=,iv:kf8uB07rQwNF/rYbO1ulIRfxzkmpgU58OPCzOLaOO0c=,tag:y+pRu46HdeOnMrfGwD4OBQ==,type:str]
kind: ENC[AES256_GCM,data:m7q7HjCz,iv:5TycN29WUlB0ATAC0XE5Ju85ZJJK1nv4VeNXbC6Ye6Q=,tag:hpkS/VXjCB95/sXlneVwXQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:j13x5mnBZHheNGy7,iv:Hq+ERmgrZitWw763yOQisNx+BQXarudw9Js8wfxYYzE=,tag:s7vraUpI1QvyNq+Mdb15xw==,type:str]
    namespace: ENC[AES256_GCM,data:NxfPi9lz,iv:pGtU8ZVkmEirg3+2oa3lPQXZ/3I/9fN8nSEXVbccq/8=,tag:H2SkopwqL9gj3rBhnZppeQ==,type:str]
type: ENC[AES256_GCM,data:SRvA+r1T,iv:UKJkYdbILBsTGYLKCHe6+PeyVU0D0ktE8nYqCMduMF0=,tag:7Vg7P849BHt4QlLelcP4xQ==,type:str]
stringData:
    ROOT_ACCESS_KEY: ENC[AES256_GCM,data:qGe+5fsJ1HgnHK1N7NBjKkRE6Jn55XBvoIZgZS50PIo=,iv:vtJrSsPLo+/oE9gIaPEAKcyAJYmFOaK8RLUxPRKrUbc=,tag:NEY8YAJ4cazg6XKWkrhdQQ==,type:str]
    ROOT_SECRET_KEY: ENC[AES256_GCM,data:EeMVXMhzJF9w9nDp2wpmr29NAHiW5Ls4KH+yh1XlX+Hy/wbS+SaXrg==,iv:he5yDUZvFqUlpZjVimrN/rvP+50unPRpdt0mhQ5das8=,tag:X97SwkFqn5CEC9/rQxgWBA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFaEhoWTQ4aHBVS2FmSG1W
            ZXZ4aXN0MEJDQ0hqTGd0ZnRsNXlYeXhnY2hnCndmYUlIM1R4MWU4UFZabkUvOUZN
            VElJSjMwcnB0V1FRYTlCTTQyTFl3bkEKLS0tIFF6SldlWDV6LzhVWUtlcStteXls
            MDhyRjFIMnZaUjZjSW1XcWVoVk9WMG8Kr2ALPe+Ofdda0S3wRAJQ9nfdNc1Z8wA7
            tpfuWIxoW9BYUJaHlpydO0XiEeMSmrJfW1qyJgZswZU3GrR4U1ZKuQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1j6zlq24dlzd9as6gq835980ahzelmnuu7d8ydkz54t28kzhv0csse96epz
    lastmodified: "2026-07-25T18:22:31Z"
    mac: ENC[AES256_GCM,data:jLT+9ImSEmKaj4392mcbKqYCRZ4hkfAPSA60rPAAHPN6JM5R3i23XZpmBBucACCafCAqP+aXyJmfoOyfe5iUsk/7oHzWum/0qTCSnCn9+JMojDLwg7wBhRCyTTlfrxGumU6nZqdDNudIFTUW01724JqWz8fCMH4ubkxlEFUtIks=,iv:89ydjBKlFaYeEURcmMF1snC7pJCwdIBK5D10grgrWJ4=,tag:PLLlBhWInV3HcEzJOT3TYQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
