apiVersion: v1
kind: Service
metadata:
  name: versitygw
  namespace: backup
  labels:
    app.kubernetes.io/name: versitygw
spec:
  selector:
    app.kubernetes.io/name: versitygw
  ports:
    - name: s3
      port: 7070
      targetPort: s3
