apiVersion: ENC[AES256_GCM,data:cuE=,iv:WgA3uuleENBd3oTcyBArJnQVwE8dhAlLVaXIwrdKlQM=,tag:ulFZ9QkjPMHmFw580RFpCw==,type:str]
kind: ENC[AES256_GCM,data:Qn+t2888,iv:SVY4eoBZeJmIHIUd+Na/HBkTgOjEScvkwAZkrwe0HAw=,tag:8ASWNRJo1CsmzNDkNLEytg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:XZLHsmhC84fMc6RFJvAZ7w==,iv:JMk8Q3ifJisAvZNq0D5j2urSyvnn0iH/Umkznw3QDkc=,tag:zShvIVgBw92WHoCI2uSXGQ==,type:str]
    namespace: ENC[AES256_GCM,data:PrgP2D7c3wjkh38ZXg==,iv:ST+5dYj0bSbVyDvZKXlhFrZQ38rOmaIOWY+sn66RObM=,tag:+5sD7GtNPcpbrnH/FtdQ2w==,type:str]
type: ENC[AES256_GCM,data:nUj8qZUk,iv:4sJPKc6F1tIjLYIvEOsN0cigWzMEUZ1LhioVAAO/W9o=,tag:W2sBifbRmevKIRtn7Xakjg==,type:str]
stringData:
    adguard-username: ENC[AES256_GCM,data:jFhkOrg=,iv:vOoGaSIduAk4WTZy2qwN1g2uRZ1/Wpp8cjaIlIxgXzc=,tag:220xiZPHjN4+nJ4xS52G/g==,type:str]
    adguard-password: ENC[AES256_GCM,data:511Hxr/Fk66rB2wCdXfVXtVUSjk=,iv:gQzGyLOV/wa2P6JhUDgGupDqMFAK6k4cqXj9dLWN4Q0=,tag:hN6191w0M0N+c7QVeMOKQg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuYVJCS1RCU2xNRzlYNC83
            ZzYyMy9yWGI1SnJCNDRzdXFpSTBxZ0NXZ0dRCkdxbDBRRmJpZGxETWxsQjN3QVJK
            akppQ1JWUEZxU0x2RTZQc1Z0YTNCWTAKLS0tIE0rOUp2Y2FPTzVhczR2ZlhJT3lt
            WGxWNm92TS9TODlpbE91bzhvV3VLWlEK03i2tZpatyEc1w9t9dH0S6uPaxpj3KZL
            x+Dx2HyCp4s/IF2UwzEBkrNHTZfYi9VMZRCzOxrxKDywddTTEeuGSA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1j6zlq24dlzd9as6gq835980ahzelmnuu7d8ydkz54t28kzhv0csse96epz
    lastmodified: "2026-07-24T21:27:59Z"
    mac: ENC[AES256_GCM,data:VIZBhVZ/k7xfdsyGbOjQPWiuAwlTeEZiIAonvahO2reqdXez/Ge7yHRN4LYCu1IvrKzhCTvzgimvTH7Odz7TT4XYGjVwc1L7pJp7OPUhnn0PhGWQ9KqS3+RTFHnfC1VgFdOBiuXjEL32KvUmo7MP9V6zSfLn7+cOXG//hiXWtcs=,iv:m1ZqoOKPojFmTCnZIruo4tU7LHTyef1wNC8HopslaIE=,tag:u+Jhho2+qejFgN2nbsInSQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
