apiVersion: ENC[AES256_GCM,data:3X8=,iv:bGWKBq/MrSl+8/GkQURS/qHq2dDv1WM7OdfQZPl3Ej0=,tag:NppyuHyuUS9tOQ7NNRrPZw==,type:str]
kind: ENC[AES256_GCM,data:JfkUPfsD,iv:kzTzDD7TgxH2FypqvXPgJ8hI9SLF/ToLG9tjRkc0O2A=,tag:zUkEWJTaz8aMEAJwpBj/Zg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:rOG/jVGn+GIdwnxe2Y0J,iv:7k9biPLmK2+7vU1m8o+IxDIFW1mvmPCGUKd06902bmU=,tag:EZwsx5Lcar5oP5VYZcNjug==,type:str]
    namespace: ENC[AES256_GCM,data:aXwzMA==,iv:R8DRskxhd45uaYC14doBXBAwPymXeMDNYqSZIEDKJlE=,tag:K+cp6xYXGZrgXAXRLHp7GQ==,type:str]
type: ENC[AES256_GCM,data:C1uBBChd,iv:LFPHYuDWYdP3riJxRG9DkfCHP7zP+6A2NU3RAtbngsI=,tag:xFLkP4T++M94zyFYYJ2VKQ==,type:str]
stringData:
    jwt_secret: ENC[AES256_GCM,data:MKn/pig/RMEsaWgJTTmGVb0mAJVKUlNMKLUnzpWseVI=,iv:uvvhWLp7X7JU8TA6d3BbJXhWSn06Z8xEpNowZK5eLds=,tag:qQIUPGreetQ8KLPsNTGh5Q==,type:str]
    jwt.secret: ENC[AES256_GCM,data:nezE5ybams1fyYQxgg+Zn+2LGdYav03t8kgUAXl3I7s=,iv:HIjqaaavWwaSxzLbvPT+30Eq5WOLHSiMbIUt1MPs1gQ=,tag:ZSoSitPBp8OJqx1v8nXy7Q==,type:str]
    identity_validation.reset_password.jwt.hmac.key: ENC[AES256_GCM,data:TnMI/lQ+O3sj1fCbd1qZ6pIV1qQ+Zf27iKKtomvtBvY=,iv:oMDXIRjweTXpw+txcl+JYfV3haOV/NkI9FBXD6uuMRI=,tag:IXr4M+DD7+CHfr5ibK0n1g==,type:str]
    session_secret: ENC[AES256_GCM,data:z37l1e0yJPBs5eLrel7Ro6o4Y+W+kqnwcumRNkiP38E=,iv:HEL3NQNWEvgUMsOW9Jk6HBqXFUnYusI4z8dJknVyw0Y=,tag:oWJC4OdlOsunrOAnA3gbtA==,type:str]
    session.secret: ENC[AES256_GCM,data:JNjv6vBcCpn0nu1OMKChgKIWgy24ZN4fExS6+D9kWQU=,iv:Sn1sfWZJdj67aNA15YFPIB705K5yqYg0m8h//gEQ3Kg=,tag:COYrZImcRoUJHbPlW4oGKw==,type:str]
    session.encryption_key: ENC[AES256_GCM,data:9k0DUJREA4r5tMXvclU68y15jzoN6sxOwl684xDj5D8=,iv:rRMF9QWOlyy+HDkArD9SaOvfjhWlviLp9RGUvk9GcK4=,tag:ezQYGb6Wkt66Gm7z/z8ncw==,type:str]
    storage_encryption_key: ENC[AES256_GCM,data:pV0YYj/do9ObtsnnytFrm40vvHRaaF9P4byMjMYCoYk=,iv:eS9Ng6frvwEHwTI83/mgamKZUfAjQ03xuVSwajxGtOY=,tag:vIztE6i5Sl9KW0S+LZzRAw==,type:str]
    storage.encryption_key: ENC[AES256_GCM,data:sZ2oxYDFZ3f+hE9A6ObU8aCGMoaW8SGnAJ3E+sb0Jys=,iv:73z3TGyIV7V66wjc1xUhaCvciDNxuzv0257QS9EzvLM=,tag:/GHN5dWsm3S7nLuAf+iKkg==,type:str]
    users_database.yml: ENC[AES256_GCM,data:+villdlzqNNxupH1V5MxYCWKvTX90mHybNsN8YxV7Gu52f8JJe3c4KK5+DcBWhjJ0cdBD6wjuIndgpvA4vrjgFgwonBsEOKBkW6dfv44KbHp1bojAe0BqzfQsL74mExr+oN3s15tBmN0ilelu+50ORiJp1eF5KnIXqNjnNAVSJgVHA4fQVRZG4RCl1oYXmJ4lUkCtDBzLfrwkxH/xJYLrdXUcCzupBnwSPRtOZP0r+NnmA5FoGHZV6su0Jka/TEdZ16OZX155KiunmbuaRnfyogKxO6kOooKHzdKjlWrEKGyjui0A1sqlhGJ2Mt2nDB761zDnww7KUlRzLo=,iv:uvs/V4gWYMJW2Ht0uMMoMjoKXsTyyOt2W+IFC/cxkHM=,tag:r2NCqx81EyMQH99FkIRj5g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6ZGVNNWFQZFZLRWJGK245
            Tk4yNlJFWTdTT0syZTlMai9OK1lIdTdiUG1rCm9YcUFLNmNuM1JsWG96UW82dlhp
            blJFWS8wVmZFYXBOVW9JNTNBdFBmZDQKLS0tIFVMcjNFUHM5dHN5YkpXYmVSSytQ
            ZXA3LzB2Qnc2WnhKWkJnOFFucm1TSlEKJijSQXHX/hCQAZdNj1DVigbl66WJqyX4
            IqOyWTP+WTqbFbVwbU8INa6ehKC1QnQbRP2J3tnc/0Jy3pk1uDcFrw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1j6zlq24dlzd9as6gq835980ahzelmnuu7d8ydkz54t28kzhv0csse96epz
    lastmodified: "2026-07-17T17:50:48Z"
    mac: ENC[AES256_GCM,data:G1V0GBzmJANTtzzsE4z2fr8Ky+maS7vsOl+D4gf3O+8TW6tLqdAAOv9n4nRtfzFHu80gIYss4hji4ExdBG08JuuT4GtwcdVr/oJLu9oEIHGHzolq53DlNusf/+TfZQabw5fF/kPHRi50NrlQWs0ZHKeMHB6gFekqBiaIrCp5S88=,iv:ffA9a+2LbV9SgoEd0kfT/meECnrpWfh1pHUetP+pQPk=,tag:/yC2viQGdagKL8XCesPTKw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
