apiVersion: ENC[AES256_GCM,data:ovo=,iv:5w2QqguqwgvBRD/Q0WvYS20b+0q0LS+jmw9bhnWD5q8=,tag:SSSVdvT1QO+2ZpKBUKyRfQ==,type:str]
kind: ENC[AES256_GCM,data:Ck9+p7tu,iv:18FyvDzVbrDp6Ao07J2tlfXJF0j5vrXglWzPl46Ovaw=,tag:S3ZUMFj5qcUjtiSquVjIEg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:QSCtZNx7HwE4pR5l6YX8,iv:5ze1Mx+FvPHADWLVufGflkTywUgm1hfjW0DUVh8m/TE=,tag:p58IhjPSUXQBnhByE89mUQ==,type:str]
    namespace: ENC[AES256_GCM,data:XklWJw==,iv:sMuNfkyY+8hGwuAaffuoP+xq3QQvNYxNfCsDlVXgnkA=,tag:j2OEjZk2mzEJAdu2P5qZUg==,type:str]
type: ENC[AES256_GCM,data:G4eAi7I8,iv:4yHt8dNf2uWplwWBOxtMi2F0ngvMoXNBpB+Oo8P96L4=,tag:1DPA8YpCK7dAYe1DBPZLVw==,type:str]
stringData:
    jwt_secret: ENC[AES256_GCM,data:JpbHmTcDis+QLnT2Di0Em4ogj8Aiuxda792kR+4ho9I=,iv:uwFLYy8zsRApdS/Hn/k7+H6J5eYKnJ+EBm0uQC//ce0=,tag:UI7XWCO+0/zgy70lHJV/qA==,type:str]
    jwt.secret: ENC[AES256_GCM,data:zbMd1HpYhtAr4W0lZbwL/efQtTbmnHVEy7iaw/GCzMM=,iv:B958hayf1Nvcok8cu9AGeVLYCdNI2QpR7I7a3f4wYLc=,tag:SPWBjJ+SoWG94+EHVXGBqA==,type:str]
    jwt.encryption.key: ENC[AES256_GCM,data:KgzdXFDLULN6Wux0ADNkdXNyB+UYbnugcV30O20GsuY=,iv:V6D/7gid4Fx6nV03J1yId5rdhdXM5TLvTmwTYthv/DI=,tag:kQSRQkQVPxv3XwgwGTcL4A==,type:str]
    identity_validation.reset_password.jwt.hmac.key: ENC[AES256_GCM,data:MXw4U0jRqzhKMh5CyJswwvBNLedTfiTIt9jnxlcr+gw=,iv:K/Phm2oqH5QXLwaHr/p9iaYLYCDXSrMqoPlRiLlt8aQ=,tag:I9Tx3APcMSSOhQ+t46Lk5w==,type:str]
    session_secret: ENC[AES256_GCM,data:oIvNFAClOvblXs8FlVyNLhMnR+l5qYCr7S5eFTiDVZc=,iv:2v3QicqkSuAYGaCc1LC4F6R3RzmoNzM3aoAyfYRDJsI=,tag:GL+nVsWmyHAN/IZ6e7PCTQ==,type:str]
    session.secret: ENC[AES256_GCM,data:GKPTsqnajh/88EflT9g5yJG3nmceS8X63TXT4ChXkYI=,iv:zB+ogbhIALONe5OPvhrCYHtBq9scYnia1dBasK5K+Nw=,tag:gty3dyOgwdALORTKr+sugw==,type:str]
    session.encryption_key: ENC[AES256_GCM,data:FrqT5BncH4nn15k9qNks4auvOfaS942xN1eovet9UjA=,iv:37RwORU6P15HimuKKZmVe2T9U56lbwyGiV7XWjHerbs=,tag:dlgVTSeFPqHnXxsSlDFWZw==,type:str]
    session.encryption.key: ENC[AES256_GCM,data:0yCoboJlOkXf52bzlhBfC+gjBX4f2E840/QD+OHq39I=,iv:u03KU0jYmp4tReaNmOzn8ZosmC/dcpzXvobfL1BEKis=,tag:erULIzxqUSFXVHCkc/uVjg==,type:str]
    storage_encryption_key: ENC[AES256_GCM,data:Y8XYjo/AtxS0iNSJppEKXAaz4piI5yuVTq9UlIHd4EI=,iv:FLbVMXRHRae2J2LyvkKXFjXbJKs6r7RPMjLTUxtjTNE=,tag:z9h5TbBVkJi+88/VpiLt1Q==,type:str]
    storage.encryption_key: ENC[AES256_GCM,data:dtS3DNbM42MnRHIoELrjmMEx5Of+xmmcHkqTuGYUscc=,iv:PLUAGTFYFzaJd7LMOf0KnHy1Zh27/XySiexsLTKZn0Y=,tag:gzNabiO7z4GkfaP9Pi3Wrg==,type:str]
    storage.encryption.key: ENC[AES256_GCM,data:EfTaVLr2SuqFVnRf2MrvV4nhaDQ/OhunvGo0ft/DOEA=,iv:tDuuusUyyGI1AObktqRd5ZsRxzTXxdixOK476IS9cl4=,tag:WhvN7q/xAHcRl9RqMtwZvQ==,type:str]
    users_database.yml: ENC[AES256_GCM,data:Y2PonZteLZKfTIO9LdzoM7SxgbTgxihGLO9E8yUMPXPt3nQuOGMmOVhpS1WdWnZvr3vObQHhsDe5ppCz1gmy++eWq0C0yKB2KJFbeFkkxmZbN/PMg0nlqiTjQuggqVU5jKwlTW15n7Ztu0YDa3YL00GRYsDS9QKMgqeD+cGC6WDUoVJKWvDhhBOZ+ckoPSiYdN5HwDXAicW3ys9PhkKBgF7jiMWTHV+6z/oBl9qtIoPMT4kJxJG8LvFyKuwb320SK9uF2K6flphRaENhlgiv8vdlmcy0NxhkXuCbkkXF5HSR9ZgtnokvWwLppQ7XOfVP045VQoUXkHtL8CM=,iv:QU+gj229Lx0ZZpJFYeIief41q5M6yZfuq8f2/0eed/4=,tag:CuH50uf+ZTFrYrI0Jdmchw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZOFJWSHZMbnJYVVoxV2Ux
            Z1F0a2NpVUhha2tMSkt4VXcxZHhoMHZOU1NBCnZmeUdSU0ZkVWZtL1h3cUlZaE1P
            RzQ2Y1JiQ1l6QXdobGpJM0lOcEZzcTgKLS0tIGdUK3pKU09FSEpJU2FOVmp0S3h2
            QXplYm5xZ3E2cVFwYUE0ZTAxMTVVTVkKxcNyb5hlgCyJt9EI9AOhHA0TUBxizDz1
            b9Oz7M3NSXXAp/Qu9KAfu6ziaUt0mmMR5Ft7dDJNuhhvRY+i5al6Uw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1j6zlq24dlzd9as6gq835980ahzelmnuu7d8ydkz54t28kzhv0csse96epz
    lastmodified: "2026-07-17T18:03:05Z"
    mac: ENC[AES256_GCM,data:CvYygX1PSTyNCqwsYMsD0YoejvT0yfVY5c5vCxH0CvxlLiefs1eg2++/M4NuQEbvhWkfavoVcY7m2low6L0UGxwHngPInpWFeAexzeyvuZoJqPQn2gGhH5Jj3/QmWqzO0oIe8EsR5mB9ud4CnPIxdiFrb2pJIJXC4eV7YYtk1Uw=,iv:R/BUnn+ocMhpRs+p1f7ddgVdxQkKYUNaEB/XHYpGpPM=,tag:W9/1VkjfNQcjCrfSvdOUaw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
