apiVersion: ENC[AES256_GCM,data:YUo=,iv:LXkEW5RnZZbT3qaqxox3RrCsGkgPvm8OyAHbuW9gQXE=,tag:Teul/mvrkvosK/QVkjID2A==,type:str]
kind: ENC[AES256_GCM,data:LQfeks9K,iv:1I7mggyjZUcvDxwBcQYXmmN33JSwYCkDqwsxSFo7R14=,tag:rATIUCDHXMTYRGJ2LHG27A==,type:str]
metadata:
    name: ENC[AES256_GCM,data:1D17ACs62swIMCm5xSMS,iv:FbTjaEkm6BXj6QkAbYsMwkNHMy8NPJlFVd4JGw+CMR0=,tag:2mpXMIUynneA9OMA7LdVeA==,type:str]
    namespace: ENC[AES256_GCM,data:4g2t4w==,iv:q4+AKVK6P1dGVYRCP9+Kgd3vMN32/FvUqf42LheOtU4=,tag:/UQ2bduRFF71/nCyRnC1WA==,type:str]
type: ENC[AES256_GCM,data:Yd0jqKh9,iv:W1FHWwwT7wv4QuJU8kPB9kL5VL5vF7pCasyGPBW++xQ=,tag:Ymz8HkgZHTORV/dw4SeMTw==,type:str]
stringData:
    jwt_secret: ENC[AES256_GCM,data:8IEuV3WitGCA8jmmxaizcB92nn1zZJktLIzrdNOveu8=,iv:uwDxg3eE8bP3QUd7mZ20v3WNIXtF62O9AFtvrq5cs9o=,tag:NStGlasHzhjq4qo7/vJndA==,type:str]
    session_secret: ENC[AES256_GCM,data:2iVZd6RwLx+ukmdTXmTNFWRV8xv+VKpQhCHIxLl0jGw=,iv:wy8uqcdjrAUy7z/J7BHmPBnN0P311iZrEMnyeoQ2K2g=,tag:TbTRdkM2Am2o9Cp2cInVgw==,type:str]
    storage_encryption_key: ENC[AES256_GCM,data:8iZ87zYsOolny9uDVht49dlqwm4lEW/RgQYcAh8YkQQ=,iv:wxrhQXoUxpIHXh38D2WRRGdsZGRlkL7f8zU+Pflahbw=,tag:cvykaklfErCKqhokeA3NwA==,type:str]
    users_database.yml: ENC[AES256_GCM,data:Jeb08SsA2iEjHGPJ3CnHZPaSCibTDdPT1Dr4BNx8CGJQcyT0+YveFG4ABCVP4m5KptBpcJSdF4s67JcU97ZpiyWkI7mT1ILDwFs5nQugzr+H8tNG90o3B0/TKUeKe6U/HaHrNcRCYs9iDXpDlmh1Vekh6jZndIbtUV1kl6a+8lXKvRyuZJ/2eOuQebskh5LTYFJtFUhmR31Lq6cmMFoLbFKua0Oyk6oCc7hkBb1FsNLwZ90Fw03gEjBxdxbiJ8qNT7si1ERRImhOZBZd6fJY95aovWDY2MNCvCI6nt2zlEDaPxirdcB8cXr46NsxN+6GhnFRh9KxDLP7dtk=,iv:XbjUt5ywVB8qI7mhw+sgNpEpD+q9sPsOxArjpdbYDkM=,tag:ARq6JIzHMlD4SXklfRkbZw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCUzZ6b01Qd2ZMTlNHOTBZ
            K3kybldHbjNFbTY0VjZadFVtN01JRlJudkJjCldlY3NpdmFjTVc0blJEeFVWbGc0
            MmpHcEdmdWU0QVlUSWt5M2s1Ti9wWFEKLS0tIDJPK0RtVkQ0NFFFVFc2MkEwY1lL
            dXF4eFZkeWgzZmRzdDQ4UmYraFV2d2MKnzD6He6vuVe9aOCb/rQOQ29CHmx12cU9
            4YZGSbyKOb+QDodTsmJf/bg+a+A1LWeWBv/dOmLBsqnFkIh3u6seJg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1j6zlq24dlzd9as6gq835980ahzelmnuu7d8ydkz54t28kzhv0csse96epz
    lastmodified: "2026-07-17T17:41:31Z"
    mac: ENC[AES256_GCM,data:yXt4QrL7r94V2R3QBpbC7uBNqFvSOdrKTMZWkMQ2mpQzEdFVcDyTY1gdDFftxK4HhAgqNejbkm5zqD+fWgnx/eFy4kmnWDA8U/gyEgBuE39kJQIFvPcK+QAFf7wFflYz3RaB26WufEImi3ia3QH7fIgjZtO4PE6OkVmW3k0Abl4=,iv:ofdxXYhJ1oC8CwMXKS6smeV0FPhPTcoQN5VjrHGSWqw=,tag:so3CnoyqrhvtsyYpISki8A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
