apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: frigate-config
  namespace: frigate
  labels:
    app.kubernetes.io/name: frigate
    app.kubernetes.io/component: storage
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ${STORAGE_CLASS_SINGLENODE}
  resources:
    requests:
      storage: 10Gi
