apiVersion: v1
kind: Secret
metadata:
    name: frigate-secret
    namespace: frigate
    labels:
        app.kubernetes.io/name: frigate
stringData:
    FRIGATE_RTSP_USER: ENC[AES256_GCM,data:K6TJ6so=,iv:OSPEYk+HUNtTeV909p6yPhHUegZljhP7g4l5HOhgACI=,tag:f0HfJ6oDXx9vlKHN/fOfEQ==,type:str]
    FRIGATE_RTSP_PASSWORD: ENC[AES256_GCM,data:DRJ7wxhHatB2YGCSFVnt,iv:GSwe+JsyXL9NBlPnCDR5JUkPA3HPMY2Ae2GcBRUZ7ho=,tag:i2SuwErvbhuYGRZWSz64eg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPUmxld0hJcTRwRHMvZHQ0
            SkQyY0U0VjMyOVg5RnE5ODJQeGYwR25HcHhNCmI0Tk1qTU5oTTYxQkVUbjZqQzUy
            bjB0a0dod0xubUhlbkowdlNPNG05bTQKLS0tIDRzejdZM2p0elZZanNHajdlelNM
            cHRDSDI4M1VTWkc0OUtLSjN2bzhzajAK4Qeufiuzv0ihpc18uRQpQBKVeqsw7HFK
            /WvGIHoTnX5k6HSaukTDgyvt/8UijLPS4Ekced81uD+gUOV+lgkOZA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1j6zlq24dlzd9as6gq835980ahzelmnuu7d8ydkz54t28kzhv0csse96epz
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-21T18:32:39Z"
    mac: ENC[AES256_GCM,data:5fXmmRcf1l4n3vE/YHboK8VoRW6hkb2snn/whzDG7eoeXHnGPTClG1xZrsY+DsDhGizITiAlrp1Uz8hQTaP1OZ0V3PbOUDSh46UHKD/N4HwhNnW7FhnuLzfOhdvFHerFBSsP7LUIpfd2KPdiWx2bWhwqFdklNjJP0jIQ3lVCZLA=,iv:WgbUkxKfjQSDCfrxr6AW0lhP3jgg0mOdPm1T87hQuuo=,tag:4fZLfFDr+P+2XSGPNXHy9w==,type:str]
    version: 3.13.2
