apiVersion: v1
kind: Secret
metadata:
    name: frigate-secret
    namespace: frigate
    labels:
        app.kubernetes.io/name: frigate
stringData:
    FRIGATE_RTSP_USER: ENC[AES256_GCM,data:K6TJ6so=,iv:OSPEYk+HUNtTeV909p6yPhHUegZljhP7g4l5HOhgACI=,tag:f0HfJ6oDXx9vlKHN/fOfEQ==,type:str]
    FRIGATE_RTSP_PASSWORD: ENC[AES256_GCM,data:DRJ7wxhHatB2YGCSFVnt,iv:GSwe+JsyXL9NBlPnCDR5JUkPA3HPMY2Ae2GcBRUZ7ho=,tag:i2SuwErvbhuYGRZWSz64eg==,type:str]
    FRIGATE_MQTT_USER: ENC[AES256_GCM,data:ljA2g6ZeLg==,iv:foFQkbLuc1HUSFgd3mWDOPaPaaoXRxm9rCXNWo0tL1k=,tag:koSSt9ONfn4PlhWp3SdZ6w==,type:str]
    FRIGATE_MQTT_PASSWORD: ENC[AES256_GCM,data:hPdrGbXZ0XWRDAURxL0m01cClmCjMnyH,iv:OgVJNOn/QZ8a8cpixm5cEv+KmrTE+b2mLsdx45W8TYI=,tag:z1vDsV20Ze7Qwn4HOaRonw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPUmxld0hJcTRwRHMvZHQ0
            SkQyY0U0VjMyOVg5RnE5ODJQeGYwR25HcHhNCmI0Tk1qTU5oTTYxQkVUbjZqQzUy
            bjB0a0dod0xubUhlbkowdlNPNG05bTQKLS0tIDRzejdZM2p0elZZanNHajdlelNM
            cHRDSDI4M1VTWkc0OUtLSjN2bzhzajAK4Qeufiuzv0ihpc18uRQpQBKVeqsw7HFK
            /WvGIHoTnX5k6HSaukTDgyvt/8UijLPS4Ekced81uD+gUOV+lgkOZA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1j6zlq24dlzd9as6gq835980ahzelmnuu7d8ydkz54t28kzhv0csse96epz
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-22T07:10:49Z"
    mac: ENC[AES256_GCM,data:lcMszGsiLTJm/lGmJZW4iizJwJp9tjxYX2TtpzB/0CTN27GseJfvAuFmUqhikm4OOsU/QMPWDsZDVR7oqIFheGTNcZcD7smgG5IQSiYccqcD/ap9Hx9yZYQV6hjX6SColnJ5nagpxV1HMtNc+k21x/86vFPcAh8r5Rc5BG9zuYg=,iv:QVvKG9NjPi7URO+59+67MT/J3+bJV0jebADcfPb3sDQ=,tag:w2oZJg12pbB/Ux39bh1fxA==,type:str]
    version: 3.13.2
