apiVersion: v1
kind: ConfigMap
metadata:
  name: legacy-dns-config
  namespace: legacy
data:
  Corefile: |
    local.${CLUSTER_DOMAIN}:53 {
        errors
        log
        hosts {
            ${OCI_CLOUD_IP} llm.cloud.${CLUSTER_DOMAIN}
            ${OCI_CLOUD_IP} oci1.cloud.${CLUSTER_DOMAIN}
            ${LEGACY_MQTT_IP} mqtt.local.${CLUSTER_DOMAIN}
            ${LEGACY_MYSQL_IP} mysql.local.${CLUSTER_DOMAIN}
            ${LEGACY_POSTGRES_IP} postgres.local.${CLUSTER_DOMAIN}
            ${LEGACY_REDIS_IP} redis.local.${CLUSTER_DOMAIN}
            ${LEGACY_VPN_IP} vpn.local.${CLUSTER_DOMAIN}
            ${LEGACY_DNS_IP} dns.local.${CLUSTER_DOMAIN}
            ${LEGACY_FRIGATE_IP} frigate.local.${CLUSTER_DOMAIN}
            ${LEGACY_HA_IP} ha.local.${CLUSTER_DOMAIN}
            ${K8S_NODE1_IP} k8s.local.${CLUSTER_DOMAIN}
            ${K8S_NODE2_IP} k8s.local.${CLUSTER_DOMAIN}
            ${K8S_NODE3_IP} k8s.local.${CLUSTER_DOMAIN}
            fallthrough
        }
    }

    ntp.${CLUSTER_DOMAIN}:53 {
        errors
        log
        hosts {
            ${NTP_SERVER_IP} ntp.${CLUSTER_DOMAIN}
            fallthrough
        }
    }

    ${CLUSTER_DOMAIN}:53 {
        errors
        log
        template IN A {
            answer "{{ .Name }} 60 IN A ${LB_WILDCARD_IP}"
        }
        template IN AAAA {
            rcode NOERROR
        }
    }

    .:53 {
        errors
        log
        health {
            lameduck 5s
        }
        ready
        forward . 1.1.1.1 8.8.8.8
        cache 30
        loop
        reload
        loadbalance
    }
