apiVersion: v1
kind: ConfigMap
metadata:
  name: legacy-dns-config
  namespace: legacy
data:
  Corefile: |
    local.example.com:53 {
        errors
        log
        hosts {
            203.0.113.10 llm.cloud.example.com
            203.0.113.10 oci1.cloud.example.com
            192.0.2.104 mqtt.local.example.com
            192.0.2.110 mysql.local.example.com
            192.0.2.102 postgres.local.example.com
            192.0.2.103 redis.local.example.com
            192.0.2.108 vpn.local.example.com
            192.0.2.107 dns.local.example.com
            192.0.2.106 frigate.local.example.com
            192.0.2.105 ha.local.example.com
            192.0.2.11 k8s.local.example.com
            192.0.2.12 k8s.local.example.com
            192.0.2.13 k8s.local.example.com
            fallthrough
        }
    }

    ntp.example.com:53 {
        errors
        log
        hosts {
            192.0.2.7 ntp.example.com
            fallthrough
        }
    }

    example.com:53 {
        errors
        log
        template IN A {
            answer "{{ .Name }} 60 IN A 198.51.100.1"
        }
        template IN AAAA {
            rcode NOERROR
        }
    }

    .:53 {
        errors
        log
        health {
            lameduck 5s
        }
        ready
        forward . 1.1.1.1 8.8.8.8
        cache 30
        loop
        reload
        loadbalance
    }
