apiVersion: v1
kind: ConfigMap
metadata:
  name: legacy-dns-config
  namespace: legacy
data:
  Corefile: |
    local.homme.ar:53 {
        errors
        log
        hosts {
            129.151.125.247 llm.cloud.homme.ar
            129.151.125.247 oci1.cloud.homme.ar
            10.0.11.4 mqtt.local.homme.ar
            10.0.11.10 mysql.local.homme.ar
            10.0.11.2 postgres.local.homme.ar
            10.0.11.3 redis.local.homme.ar
            10.0.11.8 vpn.local.homme.ar
            10.0.11.7 dns.local.homme.ar
            10.0.11.6 frigate.local.homme.ar
            10.0.11.5 ha.local.homme.ar
            10.0.10.1 k8s.local.homme.ar
            10.0.10.2 k8s.local.homme.ar
            10.0.10.3 k8s.local.homme.ar
            fallthrough
        }
    }

    ntp.homme.ar:53 {
        errors
        log
        hosts {
            10.0.7.1 ntp.homme.ar
            fallthrough
        }
    }

    homme.ar:53 {
        errors
        log
        template IN A {
            answer "{{ .Name }} 60 IN A 10.0.21.1"
        }
        template IN AAAA {
            rcode NOERROR
        }
    }

    .:53 {
        errors
        log
        health {
            lameduck 5s
        }
        ready
        forward . 1.1.1.1 8.8.8.8
        cache 30
        loop
        reload
        loadbalance
    }
