apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token
    namespace: flux-system
    labels:
        app.kubernetes.io/name: flux
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:cU8HQLXj6HFzr0p7evB371otOm9GU9ztLrr9iFwP5F7b5SufBnuXSsZm0d0=,iv:81CRhzJf6rtdGEK+OkDAKP/cg+jkELB6gRoRBlydzvE=,tag:9iOnBxOYuGpvGLkyqah+pA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMZUVtM0tqc2Z5VTFtbThn
            cEhuNDBraThIMTFXWk04WENoeHVsUllRZFhJCmNxNCtIcEd6aW80VVZldDZDU2ww
            M01IZVpjQ3M3bkdtOU1KTUJNdFRZUzgKLS0tIE1aT2lIdzdGZGpzRFoxeW5QSWRY
            alNQMHZKVDVSa3FwZnBDeHN6cTBTRXMKnVNxmWI32CtN3r18t2sJvyf53HLgqvc4
            OsOdoFDBsmmu8mXAA7ANTUpQxazp0cesV58+BZRyv9IogFzt1v/7mQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1j6zlq24dlzd9as6gq835980ahzelmnuu7d8ydkz54t28kzhv0csse96epz
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-29T14:26:02Z"
    mac: ENC[AES256_GCM,data:Qs0nddgiFpvqw85db8CvU4Z4co6dFZZsEXWSXpyOUHkfqARNLii3nb0vxNzqcJUnmNASJIyc5MEAozc/dRrWmevQovMvufKlWDPVTKOgwS3b5FFWv3jJiYyW76V8EWdreJu1S0rDFbkDMoETF8z5l8oDGygSZM8rk9i1+QVIDEk=,iv:lQDYdS5nuzfbuvm1/s3lKopbUiYbsb8pHhj/dbmIn64=,tag:F6umlywh+iazBzFdK/wDwg==,type:str]
    version: 3.13.2
