apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-vars-private
    namespace: flux-system
data:
    CLUSTER_DOMAIN: ENC[AES256_GCM,data:HXpgEBLl4IU=,iv:AzwxBbLmZQ2Fcg+xH0xIabohVm6J1tExeWY5vXSGuIE=,tag:qSBMNgSHIarHFCSZZeOL1w==,type:str]
    CLUSTER_DOMAIN_SLUG: ENC[AES256_GCM,data:9cWfI2txx0s=,iv:VXUzivLV4YKI0a1vmMC9uIbn7AdkiQP6bth8URS+114=,tag:j3GbQxrOKxrxZ1d+jG17OQ==,type:str]
    ACME_EMAIL: ENC[AES256_GCM,data:FeLnhINs4BniCLGwow7DCJjRU/r8Xks=,iv:ux17E1sHlyxkjSyb7IZsz9SxxuVmJyTqUs1H1GYvNcs=,tag:uhiFQODTlMvU1SRIQQoitg==,type:str]
    LB_POOL_START: ENC[AES256_GCM,data:HhnkjII3i9vn,iv:NyrFQPeErZ9fqSNC0E1seIH2UTO8J+9rzhi3AqRMsDY=,tag:LdCCpTmus1K68XSSag6AIA==,type:str]
    LB_POOL_END: ENC[AES256_GCM,data:VL3Qwk/7Sfzi4Co=,iv:Z1r32uxVJ0WHDUOKL/TUSNL6uNC8ff1DgucMftSeWh0=,tag:SHdROkplUjJnYc4nmRLRNQ==,type:str]
    LB_WILDCARD_IP: ENC[AES256_GCM,data:F/I51Xqm1gF+,iv:Zdpzbb5v/a53BdqNjD2HD0QukFC4XyZw/NwfqZ6rCKo=,tag:za5ztcKpeN2MfS2Qe1wWGw==,type:str]
    LB_VPN_IP: ENC[AES256_GCM,data:V5NVUIZ3A5Kn,iv:z3GPx0jfdNCZBrtqjZoOLOduokJ95qZ3qg6JdJMDqtw=,tag:OUQfJFjTWbHb8wV9o/S9NA==,type:str]
    LB_POSTGRES_IP: ENC[AES256_GCM,data:dUoq6opv+NdJ,iv:4F3/sbb51ruc13/Yl+M0KOhDmuW0NJ9HNnzI6XN7oEU=,tag:sIHFZpWx/HvINgKFn+qNxQ==,type:str]
    LB_MQTT_IP: ENC[AES256_GCM,data:4eC51Y5n6Csj,iv:AC4BZVlz91zWjWv81mGRrA3tMG6Ad4ETzGBdsFtlX28=,tag:nSm7Mqcjv+FBSUgLvBrAqg==,type:str]
    LB_NNTP_IP: ENC[AES256_GCM,data:3Cn0SweKG302,iv:5QOPF23/tBXnbnQ1VAGMpvgfWKYMiQYb28HXDyafkIE=,tag:dhxvmtJBpsRy7uTh0wXdyg==,type:str]
    LB_FRIGATE_WEBRTC_IP: ENC[AES256_GCM,data:AIXBNCMQ0tuJ,iv:1bEEb7Os4iHcCFUYXOMyfGkuCsBgjwJ4pAuMFKP1vII=,tag:Ry4HKAuLdqJmFTQiSh9VsQ==,type:str]
    SER_DNS1_IP: ENC[AES256_GCM,data:DlLpPUgU4t1H,iv:ji4Un4o9ef+YXBwxGYvBC2DVhrVKfKinfPsCJLyVMf0=,tag:tMADu2QevDaGACUaX78mxA==,type:str]
    SER_NTP1_IP: ENC[AES256_GCM,data:p3JoOXFimL6B,iv:WP1ogqiK9KQkl9fOcsUIadtovNB+9Jg6MTk2bE+KIXk=,tag:oN0DvvUMtMsLpUY6KvChaQ==,type:str]
    SER_UPS1_IP: ENC[AES256_GCM,data:9UTB4tdz93o1,iv:j3fof4jxG33Km7yEyxNpin9emfJMvYGhI2BBQ0nMUIQ=,tag:339gtsB60RY7dX4pmNMc7Q==,type:str]
    OCI_CLOUD_IP: ENC[AES256_GCM,data:ZdqTiOb78Y3Dh+3QepdG,iv:UN+N2X4eSndN9wyZfmNHi+KPLqM1tzwozKx9LqvC4Q8=,tag:vikDrJ+DDAcK8wWyspoyVQ==,type:str]
    NAS_IP: ENC[AES256_GCM,data:ckvlfsmn/Ss=,iv:kAEnNchQDokSMtRVVstuaYuJkoSiSbh9D/GFMndEKFA=,tag:EyADQcQfSa8AvKC/5Tig+A==,type:str]
    TALOS_VIP: ENC[AES256_GCM,data:QROmAlwtaHSs,iv:1oS5u50Nsw9Y3c36jG/c6uwRoTIGiqW9yksoaoFXu0o=,tag:JZqXR25dn3N8MNI10TiqZg==,type:str]
    TALOS_NODE_CP1_IP: ENC[AES256_GCM,data:6Gp6diyq+p1p,iv:9XKtKkcWPo718xC070yiLufgOqaatl/x3tlh/8CA9XQ=,tag:z/isW3EIDr2OZKFx1aHqLA==,type:str]
    TALOS_NODE_CP2_IP: ENC[AES256_GCM,data:MqLn2FgilB+R,iv:bY5oQfTtz1CP7n622XCeL3+iwOZq6zMozKaQhiOIOA8=,tag:gPgdD3BPHamJEdZf8ISFsw==,type:str]
    TALOS_NODE_CP3_IP: ENC[AES256_GCM,data:wGnE0SvzkM2V,iv:V2G1HMoxH3SjO1bautNMeRoGyGJvkjOaeBHqT6JK1xY=,tag:NbPzW86EIPB6WJWQJGJB8A==,type:str]
    CAMERA_IP_1: ENC[AES256_GCM,data:zF7LylRk4kE=,iv:PegxVNEHLCylpz82mHlmuqAqwq6Ti1koP1aeisAFT9Y=,tag:nuF9HWB9+vAlFZmQQbKNZw==,type:str]
    CAMERA_IP_2: ENC[AES256_GCM,data:QlxpYY9o7C8=,iv:RZjr5/aoPzlz1OnCM2cbuWJg0DZvpNBfldVSYqJq9Tw=,tag:Pna7tGMTShGoy2oFhGMfHA==,type:str]
    CAMERA_IP_3: ENC[AES256_GCM,data:vSxT0oRyFfI=,iv:VwqBVyI3GXoLiZr8TrcvJVYT3eWeX2HtE4sVxY0UoDg=,tag:XOVmuqwdhjUzTm+xGn/+/A==,type:str]
    CAMERA_IP_4: ENC[AES256_GCM,data:GkpF230u+YY=,iv:gpODQX9T9Qxt8Xrg3IrylnBjFt/lG6HQC39RnkUz0y8=,tag:64NyHbAWAppffsSAPRORBA==,type:str]
    CAMERA_IP_5: ENC[AES256_GCM,data:4r+7yn0+3xY=,iv:znAQMdtC0cr568V+f3UdUdFSb7lg5oSRbP7HimUiHH0=,tag:DmDdXSoTyo36+l7vuDsvfQ==,type:str]
    REOLINK_NVR_IP: ENC[AES256_GCM,data:Xmsb/Oe+paM=,iv:6ga2Kn8sSpVk9AowTJfHfrqoChPq0Q9hiG4uZd0GENQ=,tag:2TaaFuXCCPaVJA4eVIMi4Q==,type:str]
    SLZB06_COORDINATOR_IP: ENC[AES256_GCM,data:eN34eno8ARU=,iv:uWJIVbzSHrdo7JLgSumzEinRDHikw7qgegvV39eyQBU=,tag:6kUPxg+VtmVSDz8scArebw==,type:str]
    SLZB06_ROUTER_IP: ENC[AES256_GCM,data:2u9De/jpYwU=,iv:l6yKgzQ+PE3po+3wpHuzQC0Mca8XGGrlt7gqEZdifKc=,tag:SWToEH+19pIDmVsUUG+AvQ==,type:str]
    UNIFI_IP: ENC[AES256_GCM,data:JDKAcA6kq/E=,iv:IlGKohFBWAu+wr9wyfIQImd63VYvCM7HegL1qHPYJzQ=,tag:KQSyu3sgDgvo21eUIT0vkQ==,type:str]
    OPENTHERM_GW_IP: ENC[AES256_GCM,data:LDbYl9fcu8g=,iv:jPrNN5hu71FhTWcfcjNCn9gnaem7tLPeyhEO8wEM4RM=,tag:JVXJJUb68HyzKqdih6JG1g==,type:str]
    SOLAR_LOGGER_IP: ENC[AES256_GCM,data:MBclonYlGfA=,iv:vVh8AJaS/dlybdolXuoHYyNsUhS+H1BpwZP4QyTpKXU=,tag:9ZyIZE+3Ki5JKY1djxqNUw==,type:str]
    SMTP_USERNAME: ENC[AES256_GCM,data:VA1I5vxrDyjMg8jOArBRSpwR,iv:ty66PVRLtvlm0557ybK8XwWbeqm5OoU81zolNZo+vIg=,tag:4ze9YmSfoeDuwVbYzyMaIg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjRGovZmZxNGNzYWp1U1Jh
            ZlR6a1diS3lKYWJCbHp5WVd6ZHRWNjIvSVhNClNYbkdzYXUyazVtM2tGamJRWjVJ
            WUdoNTVOWnB1bGFvckVuQXJTbFFHd00KLS0tIGhxRUUyZmtvWXhMaFE0bVhWZ1ZB
            b1lUR2pKaDNTdlY1VENtNWc1a095Y0UKtKqL6KW/Ik7NnqF646aM4lMt3ySllrrc
            a6hjGvkas21cP7ShJLWgujjXS2BDj8pVvP3mQUyLdcKlbj7ijA3amA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1j6zlq24dlzd9as6gq835980ahzelmnuu7d8ydkz54t28kzhv0csse96epz
    encrypted_regex: ^(data)$
    lastmodified: "2026-09-08T17:40:16Z"
    mac: ENC[AES256_GCM,data:WtzU61V1u+VjlljvuqHXgmiaEUbH5G8Hc4QYxsH/B/N/cGUiAdaif5eH7PLZWcqm3sHUUBfdw0olmT8L4eSru+IhXitvDAfs1+fCmSRggIYAGyneoUD1EeK9FDPcBmS614JPV9nZNVMIW55AFnNX/fz5GFpqr3Y9xfQz3Xm8OVw=,iv:u0po870BWCDQZloj25DAN/Cwd+vHpkAHTvuOV2cZc8w=,tag:irD1GILLRK8oxrxmiXqeAg==,type:str]
    version: 3.13.2
