apiVersion: v1
kind: Secret
metadata:
    name: subarr-secret
    namespace: subarr
type: Opaque
stringData:
    SONARR_API_KEY: ENC[AES256_GCM,data:u9XgxWNqJh0/OUFaA1Cx20BZRjcp8jWyVwIPhezVSbA=,iv:scJIWdmzR3+bxwI3gHkETBgMuvYD+PCh66AC0VFMdd4=,tag:tMpilKPofmOH7i+pk9jv7w==,type:str]
    RADARR_API_KEY: ENC[AES256_GCM,data:iNXpWXiFl9T4QjJDV28FIj9yGGRcUgbatjAj9X96GWE=,iv:kecOx1N6OxCLhXnRnNoa52EYz9TZ0KH3zmaMdm/KxQY=,tag:MPeVqPqr79PljaMoTsaqYA==,type:str]
    BAZARR_API_KEY: ENC[AES256_GCM,data:ZdiiXO7uVL1j+o5uZpM3kFo9FEHmZnIlqY7DNFwp4Yo=,iv:jTemrkNw9BKyDJIt4UzxU3jCb0/KFULFa62IDZUNYpo=,tag:ax0NXHLvofjxh40MO9USNg==,type:str]
    JELLYFIN_API_KEY: ENC[AES256_GCM,data:bsI+4pIVb14eYY6FyDY9LPl7+VgqSNzEmh0hSp//U54=,iv:Hg6egzCXtp9CcWFU0CzK4ZMR7ZnxsnU2NOaJO24dM2w=,tag:jNOkx4XWpN9DDpCTeMWI7A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEWUEvY2EzRGYrWDRzYk9x
            aTFoSGkxY2s3V3F5MWdLMk1ueDNqbCs0bnpVCnRSUHBLOUh1bUtzSFdzbld4TU9v
            SXgxOVYrZ0lHeWlhZ2xhbmhLYUlZbHcKLS0tIGNJNFk4ZFhzeitZNllVM0ZiaEdX
            NUdvbzVJTEMwaTJFS1dXU0Z1TDg5ZlEKdkT0vVdugePzmnQYdEyZaHnJo0lc7XeU
            kd8u+nVkiak9TOP+/9zPHiRSYkTgRo4ks7okfpM1lf2NAVHNQgDy8w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1j6zlq24dlzd9as6gq835980ahzelmnuu7d8ydkz54t28kzhv0csse96epz
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-04T02:29:16Z"
    mac: ENC[AES256_GCM,data:qIquGB7MN9hGwkU3nS64nGIy7DbLQ2/NrS23xtusjj+YSgDJyg8qURJgjIAhsRW6BX1+pLwEn/tFkja91jxXpl9Mt4MqTC8Os/JrToaCsKj55cjwWhtQEsCr1wOTEMcNUNw8Es8oPeG8IDGgE8DHOHXJq72NG0uBiwz4c6qCbXw=,iv:mR6ftYhUj7H/zwi8FnHQ6KhoDzcfd75SY6yDjcna2Uo=,tag:Z7XB1BRTh73IxPhR1sQ7tg==,type:str]
    version: 3.13.2
