apiVersion: v1
kind: Secret
metadata:
    name: subarr-secret
    namespace: subarr
type: Opaque
stringData:
    SONARR_API_KEY: ENC[AES256_GCM,data:qgUHxtE8zkLU,iv:YDXKTgXIVZYghvvOOGLjTwhMjeQgwwR0HG6Z8xi26Bw=,tag:OFwW/9v89Qv21znIQKorwg==,type:str]
    RADARR_API_KEY: ENC[AES256_GCM,data:Zzp832IQyTY9,iv:CDgftnOxq8NQ+OpZZBr40a/aFEbJKTcxOk5AkOwN/Y8=,tag:nFI6mpADrMPuswki31ajuQ==,type:str]
    BAZARR_API_KEY: ENC[AES256_GCM,data:ZTPPyErpCMBs,iv:gq4wp0kElLL2N96XL8KT0VXP7raqChhZ6ITwxqmfqUk=,tag:g4BiZ4F12998/zifzK9h9w==,type:str]
    JELLYFIN_API_KEY: ENC[AES256_GCM,data:WLn2nT9pqtXo,iv:FHIPy+RShgO9GKi2PX3LCl7m3sVaStryeKE6NOGdznc=,tag:mlJSgueVcDfmxak/YzwW2w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEWUEvY2EzRGYrWDRzYk9x
            aTFoSGkxY2s3V3F5MWdLMk1ueDNqbCs0bnpVCnRSUHBLOUh1bUtzSFdzbld4TU9v
            SXgxOVYrZ0lHeWlhZ2xhbmhLYUlZbHcKLS0tIGNJNFk4ZFhzeitZNllVM0ZiaEdX
            NUdvbzVJTEMwaTJFS1dXU0Z1TDg5ZlEKdkT0vVdugePzmnQYdEyZaHnJo0lc7XeU
            kd8u+nVkiak9TOP+/9zPHiRSYkTgRo4ks7okfpM1lf2NAVHNQgDy8w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1j6zlq24dlzd9as6gq835980ahzelmnuu7d8ydkz54t28kzhv0csse96epz
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-04T02:00:30Z"
    mac: ENC[AES256_GCM,data:AAY/FqWrqw4DYV/o0GbRDDjukPloWRSus6GX4rdRZxQSJ77j8yGVaKMNamuaMIPGbXEY1jsp++/hJz7rOMAdRbRCOMm5BVhOez391qUmObiaAHsyvlGHZWRPGyyJZnyFhQowXXtyBh9MdyVXX+g3gBpjtFSPLFPAqgJzs19JDsk=,iv:OOoRWcGyk8lt188KBjMtWjvRL+kmaS8gMiuLpNUwyN4=,tag:qZ72/ZZIzp6aSItf2b1yYw==,type:str]
    version: 3.13.2
