apiVersion: v1
kind: Service
metadata:
  name: subarr
  namespace: subarr
  labels:
    app.kubernetes.io/name: subarr
    app.kubernetes.io/component: server
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: subarr
