apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nas-media
  namespace: radarr
  labels:
    app.kubernetes.io/name: radarr
    app.kubernetes.io/component: storage
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: radarr-nas
  resources:
    requests:
      storage: 1Pi
