apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-config
  namespace: radarr
  labels:
    app.kubernetes.io/name: radarr
    app.kubernetes.io/component: storage
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ${STORAGE_CLASS}
  resources:
    requests:
      storage: 5Gi
