apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: prowlarr
  namespace: prowlarr
  annotations:
    gethomepage.dev/enabled: "true"
    gethomepage.dev/href: "https://prowlarr-apps.${CLUSTER_DOMAIN}"
    gethomepage.dev/group: Media
    gethomepage.dev/weight: "80"
    gethomepage.dev/name: Prowlarr
    gethomepage.dev/icon: prowlarr.png
    gethomepage.dev/description: Indexer manager
    gethomepage.dev/widget.type: "prowlarr"
    gethomepage.dev/widget.url: "http://prowlarr.prowlarr"
    gethomepage.dev/widget.key: "{{HOMEPAGE_VAR_PROWLARR_API_KEY}}"
spec:
  parentRefs:
    - name: envoy-gateway
      namespace: kube-system
      sectionName: https
  hostnames:
    - "prowlarr-apps.${CLUSTER_DOMAIN}"
  rules:
    - filters:
        - type: ExternalAuth
          externalAuth:
            backendRef:
              group: ""
              kind: Service
              name: authelia
              namespace: authelia
              port: 80
            protocol: HTTP
            http:
              path: /api/authz/ext-authz/
              allowedHeaders:
                - cookie
                - authorization
                - x-forwarded-proto
                - x-forwarded-host
                - x-forwarded-uri
                - x-forwarded-for
                - accept
              allowedResponseHeaders:
                - remote-user
                - remote-groups
                - remote-name
                - remote-email
      matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: prowlarr
          port: 80
