apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: index
resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - httproute.yaml
configMapGenerator:
  - name: index-nginx-config
    files:
      - config/default.conf
  - name: index-web-html
    files:
      - web/index.html
  - name: index-web-assets
    files:
      - web/assets/background.jpg
      - web/assets/logo.svg
      - web/assets/logowg.jpg
      - web/assets/favicon.png
      - web/assets/faviconw.png
      - web/assets/icon.svg
      - web/assets/iconw.svg
      - web/assets/logow.svg
generatorOptions:
  disableNameSuffixHash: false
