apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: subgen-models
  namespace: subgen
  labels:
    app.kubernetes.io/name: subgen
    app.kubernetes.io/component: storage
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ${STORAGE_CLASS}
  resources:
    requests:
      storage: 10Gi
