apiVersion: v1
kind: Secret
metadata:
    name: nntp-share
    namespace: nntp-share
    labels:
        app.kubernetes.io/name: nntp-share
stringData:
    #ENC[AES256_GCM,data:no4EaXU2u4wKfI25gCHMhXmnAJL3agOVWbZwsW26n+CWG0FDRRE7W4SNefHDJ8ItiQP2b+wfFlm6TNwEEk6ILFPZ2LmDbe+bmgoY6A2y6xrk0E8=,iv:ZMVv2ku/+5iIPuWekYMTqGQDsIYMsNJ8nuXTXLpnvnU=,tag:JudR/EE5l6F7I7K8rLmS9Q==,type:comment]
    FRIEND_FEED_API_KEY: ENC[AES256_GCM,data:cgOKHcYe6QKcLSqrdHgBgbBh7+4Z2uTvw/fH9OKvM5YicHBoVyO5Mg==,iv:Ri4RkWMwP7uoV+S0OedEw/hEq57YS4D6aPVHVtK94ho=,tag:Lu79zawKdEJLyLpjjSTUeQ==,type:str]
    FRIEND_NNTP_USERNAME: ENC[AES256_GCM,data:rlm+xms=,iv:Go2V47y+7LHQ2LikJ7UreFNHtz7giZA0xxf4siIhXlo=,tag:xJIK5ICCUPwZjlKBCWvLLw==,type:str]
    FRIEND_NNTP_PASSWORD: ENC[AES256_GCM,data:yDjf5PFf/tW7rVMBI8c3y3gsy6Jb9Pdh8TS0mMVPLJEbzm6f,iv:e49U+wJCO7jaE4lNHHD98oLypWPlIuzVLi8NcHdB4nQ=,tag:VJtAvksbr7x36bLpj3fhPQ==,type:str]
    #ENC[AES256_GCM,data:6q9S+5cAOLtrNK/TVZKHUUIshOJ52YgyTAoIf8GM9Qv8rxwJkV7LFWU0RLagdCiXx1ETc+G8bgDJ2DwWI8tiAxyu1baG/v2NPtwRazFzRT6t0Xs=,iv:4xulLP91kfG/OvZnid8zJZlIcbAhUGmsEN1j71VC49c=,tag:4l75SdPWrVd5n19yumJOUw==,type:comment]
    PROWLARR_API_KEY: ENC[AES256_GCM,data:CopYVXW4FdgiwcUJCZQEzaGj1s2z94zupRWnjZfGLXo=,iv:5fC3l21Y4VjTrSuosC++S6+h6joZ8wB/BvCpnE61+zQ=,tag:aAv1mO/nmwR3B1TsdKUjcg==,type:str]
    NNTP_UPSTREAM_USERNAME: ENC[AES256_GCM,data:iP9KWRK8P1muLQ==,iv:TxhqbLdleZQg5gYJR8nilUgX3BfD58d4hl7hiNV2Ibo=,tag:wvuuE/e653VMoJ0Wf9KmZA==,type:str]
    NNTP_UPSTREAM_PASSWORD: ENC[AES256_GCM,data:s2/Fe5yZZ7jUPDkZ2FR/ovWx7rQ=,iv:wL1fYDoGB0qZN+yq4UxaJVjqV+9/Td7acbv5EDDzLzI=,tag:5Age7s+PhbjRE3npztI1mg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBbU95aXQ1dGxRcW5OUU8w
            VkQ1N2NpQXpCQlpCd3R4eWJmZUR1WHBxc3pZCk0vV0pmbnFDYVF4dGd4akV6Y2Ur
            RGRqaVlMYTU4aEFncmxGR0h4WkdSQkEKLS0tIDZxQW9FSElYaWdyd3RCSmphdTJw
            NmVVT2lxK2ZtVUswc3J2S1dGZ3QyZ3cKG+Elp1tOccnbNQgOjsIhGz1IQHGynqNr
            tlIxI/Vkgxm2Xa2J+K3W3qrG12FviTEWUZ4s767dJnHneHw8H9JvmA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1j6zlq24dlzd9as6gq835980ahzelmnuu7d8ydkz54t28kzhv0csse96epz
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-08T02:54:38Z"
    mac: ENC[AES256_GCM,data:uZvfqX/qvFRdx+XFh/8gMP3Fbj1e2a1Z3UYNR8tyMvf0UgSJwt8b81T1Meiu+4wN+j1w7Aeu/v9eKDaHnVhc6t0fPU+Lac39dSklSb3h5NuU+DumI6dqBVNgmz73PhDf8ZFsB82LhFgEIYlfI/mj1pqb3otVadzUeZEEdvAHqEk=,iv:h9g2xfwALZWzgagI0QyCHk+bO/+EzaDVOiB1OQhMFv8=,tag:UOIrdzhF51yFsBXoRjFjvw==,type:str]
    version: 3.13.2
