apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nas-media
  namespace: sonarr
  labels:
    app.kubernetes.io/name: sonarr
    app.kubernetes.io/component: storage
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: sonarr-nas
  resources:
    requests:
      storage: 1Pi
