apiVersion: v1
kind: Secret
metadata:
    name: ntfy-alertmanager-config
    namespace: observability
stringData:
    config: ENC[AES256_GCM,data:MMco/sAOtAWKUUrU2pyBMo1guLHVNkT7E8P6CLqdA9mW0PymEkZnSvOvmf1deY16y5R6W7JCEHL2wY3Vfc2845GL6+AgnDfALNZJVDr7J1IlZi91K9no2ibd2udHaJisbY8XfVnVMN6jzQ8ulk1oxa+AZT0gAzfJ1ByMiKZIIEk4TN2Nq0PvTLFHg5OUF3VOr1fM/XKf0gDPRwITAwkKBp6JWEkSDcFG6DcBqlYY7C7wdbIaBNwIWmXoDVaU+QsKYncVwsWFNwlfmblZ8nRVUK5X64KHwYWB32Y62xfTwdgCtP1Edc9LrDZT89QRme27P8ouxAAF3mnkNO0GZKXTtGEzuOPjIQvj478yeYPs10pTP1V2Qjy6lDHshsOMR2GPXq99G1VpjVZyVhzGRQ/p4QMBjZjWA5l7M2hWXVyIsLJez6saHVvHL6Toor6I+IdkadIZuqMUWakODf0JgecXdAXEW1WvQa9SjIhcsMxqSua+bs92ejtGifp555mF7k+jUakGZ68YfLoViaYSVqGY7pVc9pECX4IifHcK2xzqIN9zR14gcoRGm1E/,iv:e4Z9iHERXUy60eUld4ehTIilLzXBZ6peDmu2fKpsgHY=,tag:bqifyVqVQfbrIFLEVUq9jA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBU2d4eEV4WXd3TXVQeU85
            Z090dit0aGVPRzVnZTh3R0FRMmFQRTBPT2tVCmJUYWp4RVRCRTcxZmtha1kyKzdY
            M0tDOVVXMTFRNXFJaDJJWlZYNVJLUGMKLS0tIFArNzhKbE1zczYyYnRxK0VwTUpM
            bzl6TmZycTJJQ0w3c1NLLy93WDAvaW8Kv9blNuJgoODoKH6gposVnC2kD7dC2Nlw
            1Ml0/SGFeBpfCfLHfrhLVWL8mSll0Dq5TUWzg5iMTmE2RNBvpK96Uw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1j6zlq24dlzd9as6gq835980ahzelmnuu7d8ydkz54t28kzhv0csse96epz
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-07T22:26:07Z"
    mac: ENC[AES256_GCM,data:FPq1nkvxq9ZS7yAAiw7Cufz4gsKqJB33TyUWRfT8Y2hjp/axoGbuD+roLB4GEvJK9BkdYAYj7Cdf50aabWWfn68JMwgBf0W7euLeDww/PnjouZALP9T+BFInVh/OLPRKRdgkFL3K5EeptHJ1i/j2kgxSjTvxKf9ZTDkNwQQy7CU=,iv:v5W53lEXE8S8R/ZUIIcP6wzUA8sYC6hhgDEMSaAG+ok=,tag:BPUZU56dbd9ObCWTPcSsRQ==,type:str]
    version: 3.13.2
