apiVersion: v1
kind: Secret
metadata:
    name: ntfy-alertmanager-config
    namespace: observability
stringData:
    config: ENC[AES256_GCM,data:FIKr3/F+0IAx6/kcOvH91PzpyHJNkHP7d7dggOo2cTm/62qjk6iUtyG7OIYnTq4RloLhhm9k7beXZ+YEaQUURrqXEl4XyPHQiL0AR0qT3QZd59/HeOYhovadklUt9cIjATxFhZsiyqNijMXW3QW+sOEDRvXwy6GLCauwbhP6bis8z71tjQ2HFYDCYaYlzRZP7R/N251Q0hgBwfOOKVa+3gv3pPkn5W/ZPxhjxH7B2x6alUFQsmRBBfo3pUpLtdcw4zcoBqdXCYTWsus3BYR30nt7mQtxZ44n+mDy63kK+nSM4AuIqYsm7+md1KCYEnLc0zgWxrzXYkOJ1kocxwTrpv4l8ujTHUQbqzMqFZAO8xdqVYkYweDLmbnSXOTLs6Lul5IkJt6D/Q7axamUJDmIKrCRGD5emQ7Ri3QAe8I8rjygxjJe2eIm1WO7DL+lr8xipm4X/qRAeOTvIGWEIRwOqxYaTlcDkDg7khHobLjxUQzRI7f7JJso9vp0fc7cCAoAQ84FfPj7u5QvbM5nlWp/Fx6F+wWaNydp5ZS1Yj9FplnyJ/fnQ1GFF2I=,iv:H6UYXaZZA4FaH4kMyTZToZk3V2RmPM6f9ZieUAhCZgs=,tag:e1NUzgUJMnS77sPY5So/2g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRM1YwYU1xYzJ0OG44bzkz
            c1F3K1N4UzBvUndoVjF6MVhFcUFiMjNybEhzCkNWM2k5dFRzVlFBNFNXYitaODVp
            Mk1yaFRuUm40Ui82WEJKR2w4S0k1aGsKLS0tIHA0bVM5Sm9uTmZmY1QydzZLUm9I
            anZCODJoR0RaUFJROFJoTE1jYlpnVGMKLLT0aBbvs0eLdLwqPbpLGXSxfGc1lBNM
            Yd+VX7XT9wAYMlVo2tE9xY0vGJtgMnuSL7xV2hXtCembpPj5UcpKYA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1j6zlq24dlzd9as6gq835980ahzelmnuu7d8ydkz54t28kzhv0csse96epz
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-07T22:32:38Z"
    mac: ENC[AES256_GCM,data:jBmSf7Su2PQXICoscU/ZQxM0/fSb8y1S8YsirO9ss693LSjuJF6G6JjvTioajIBCEevBzjX9/EFXmSqFSsKrOl8atMuXqDxYwXw0f9Qbf4r0FmN2/4DmOx2Awwj36NV0Aly8BaMMTAR9+RZSKWjB/qvsEXbnod5iS/eOy0XteWE=,iv:3oDSMgGfOyFJJA0Scg5s82f8QLoUNPHimPPDys2qnQA=,tag:XGbWfmeli1P95gdMgrSxNg==,type:str]
    version: 3.13.2
