apiVersion: v1
kind: Secret
metadata:
    name: ntfy-alertmanager-config
    namespace: observability
stringData:
    config: ENC[AES256_GCM,data:QwkdZgmyYQdz47/qDlURWzpKOyhc7GGflNMfDIEY7GWQGY5uEHXDwwJkCJU6naqA0MexqzbhdVuxKHvfwiAGczs2CH+sZ+M2NSi9+b3/I/6hi4tkaGy7hJlFNFxb6VlTiKLegdK+5ukaPrKebgetn9npdfkGozYjAOsXe+qibsHdMpMRnF1bKJtQpIcc7Bnt+oHAG/lBKnVKQSq+QTMNJPPbFQCE5OvR96d3DMxXgaLpRVx4UZW69gXGasItrBjP+u+wgGHqxjbtewOCn3AMPX9qvsnS9/u4e+KvbYeXrd0fTOqNOq3+H3URuTDTM3lpLPqiU+7VdoE/Wv0X4oqxXufCtOfJ0YTLfPkixdCe8L3aXBWtvknE9KxdkENSPoywWsVhJAV3xQbXEqUp0hTONTmp85/AahX7WPhJkqG7JlpVd333BlDPuYjbSJNTds96gxuejwMX+rtWt32J3lPhUrDzl5EnOoBm+ESu1r5iky5/6kLcSIpYcLYf5mIZoOy2LxR7kF2F+KgRKknqM48RvLse/fD57R58kVc425acYNG/1tbxp1jVIwM=,iv:SwZManJIww2tx2Pp7rVNHMLB1b8Vie6nD22EmKvFPOU=,tag:CkZqcWEZNoa1G/uIDheT7A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjZEhxUHlvOFAzaUEwaXZs
            aVhEaERnazZLdlZCaG9kT2IwcVB1Q2VuWG1ZCkJEM21YT0RhM3dNNkREa2puelFq
            U2tkdHBBeFV0NTdkTjVOc29pNStGY0UKLS0tIE1GOWhuelY4M2FaWTFxTXVZOHZQ
            a3ptWFhmdHRUZjVyRUlYMXZYWGF3MzQK0Jou8L30oy676qInoAw9u2ot0dGOWQfN
            meAfAbI0CcsfhhtR4FqD2lPmBSwhiaKoVgzxS6G2xKnnsq/OfCoRSA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1j6zlq24dlzd9as6gq835980ahzelmnuu7d8ydkz54t28kzhv0csse96epz
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-07T22:07:58Z"
    mac: ENC[AES256_GCM,data:yOAZ8noRav9OYzos85IBTEqS9HaLfP4Bte8io2rZCsLxMlT/5G6g5TYAYHy940gDnC4bHyxZ8Yv9tI4hBfzKpratFTOwQNM0AYs716ZC/+Ojz05QnLuuMFDHKJ7t545qfjIB++MzwkV+G8P3LnyNS88ZjVVIi18Npyy6kVwI58A=,iv:DF3AzxFMhdHzAyWp13h9aic9GD8ICXOkwkI/1Th6bw0=,tag:LhMJtmAK2Pnkhhf19aytgQ==,type:str]
    version: 3.13.2
