apiVersion: v1
kind: Secret
metadata:
    name: homebox-secret
    namespace: homebox
type: Opaque
stringData:
    HBOX_DATABASE_PASSWORD: ENC[AES256_GCM,data:vAGzEsYzZ/esexGMMT7XSyOGhzxo8MeeHFuMZV+4Kw0m1LeJZtsunQ==,iv:6eo1hkjBvJnky9KmMk4ERLCHrk97tAgFgcAksEf2MzQ=,tag:GK1kf5FP9q+buJvNgmzyIg==,type:str]
    HBOX_OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:ipgGshWhSbghg44KjFkTNS1NOfKPb4gSzzfNjY7ENOPVvyG7KYv+LgA=,iv:11eGstpMmiyCo/+l7Nzcs76LAkIAfvgKL4VnFxi5rHw=,tag:Ns81NHa8YFRzlcdU7r5EpQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6OFdWQ2lSQko4V3FaRXFq
            cTNCSlJTbEp5VTJvMHBVbWZ4NTJUUjd1ZWlFCmVneXRzekNpdkRHdnNYY2xJa0Nz
            VmZKc2pSL2RLcVJLQ3JMQVpnWkdTOG8KLS0tIHoveGxvWUIwT1Bwc1BsZloxT1Vj
            SjB1QnhDWHlQb0hVRExRWkFkNmltUlUKpXFpgpazG85ON7pYXNEmlH7SOilxi0uK
            QwzsbBAuTaR1Fphighp+4iiFnHu1Zb/Hf6J77yIXKxpuwVkdHRk8bQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1j6zlq24dlzd9as6gq835980ahzelmnuu7d8ydkz54t28kzhv0csse96epz
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-19T20:13:22Z"
    mac: ENC[AES256_GCM,data:xqWlGpkuXkwlfdDF3tWHuVwqsBuKsWFUteC+WSuvaL0ZPx6453cZUpURADc8h8uUlb2hLFmJLrVLgZ6At5YHNqD2LTHElEmiqO+HKfc95XjB+/JGvexgxrDp4bHQd3vMGZlxGqiufEQhRGTycq6+uiH9KOD6fcxDw8HuCfFLnjQ=,iv:9EE70QXGMoS61YmImqnx9D7tKj8752IrT16OX84ILTk=,tag:+ZTCGLqfhijoUUnPzqKk3Q==,type:str]
    version: 3.13.2
