apiVersion: v1
kind: Secret
metadata:
    name: homebox-secret
    namespace: homebox
type: Opaque
stringData:
    HBOX_DATABASE_PASSWORD: ENC[AES256_GCM,data:vAGzEsYzZ/esexGMMT7XSyOGhzxo8MeeHFuMZV+4Kw0m1LeJZtsunQ==,iv:6eo1hkjBvJnky9KmMk4ERLCHrk97tAgFgcAksEf2MzQ=,tag:GK1kf5FP9q+buJvNgmzyIg==,type:str]
    HBOX_OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:ipgGshWhSbghg44KjFkTNS1NOfKPb4gSzzfNjY7ENOPVvyG7KYv+LgA=,iv:11eGstpMmiyCo/+l7Nzcs76LAkIAfvgKL4VnFxi5rHw=,tag:Ns81NHa8YFRzlcdU7r5EpQ==,type:str]
    HBOX_AUTH_API_KEY_PEPPER: ENC[AES256_GCM,data:e0rPhES2b7Y0evdBZ42ixl1i2UjmfQLltv/4uA+lUJhVQ9HE6vlWk058ennrxYGjocPbNEvI0rSr0q045UbObA==,iv:Bt8gRAAt2QBQ8okrgotVUGyeME6aCbZd8Z1NEabmfEM=,tag:Ew7Y9dILiNkkCnTR6jc70A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6OFdWQ2lSQko4V3FaRXFq
            cTNCSlJTbEp5VTJvMHBVbWZ4NTJUUjd1ZWlFCmVneXRzekNpdkRHdnNYY2xJa0Nz
            VmZKc2pSL2RLcVJLQ3JMQVpnWkdTOG8KLS0tIHoveGxvWUIwT1Bwc1BsZloxT1Vj
            SjB1QnhDWHlQb0hVRExRWkFkNmltUlUKpXFpgpazG85ON7pYXNEmlH7SOilxi0uK
            QwzsbBAuTaR1Fphighp+4iiFnHu1Zb/Hf6J77yIXKxpuwVkdHRk8bQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1j6zlq24dlzd9as6gq835980ahzelmnuu7d8ydkz54t28kzhv0csse96epz
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-19T21:24:38Z"
    mac: ENC[AES256_GCM,data:qtZde+aD74x6Ffpi0/n/ttSzpJax4MxKNJrNMQi/XJDNHiK+b2qxsnKRio6B4tuQhcJELgFlQwb/SlaCD5QmB9Bm1DK1iTN/K9Ys7c4g1paSJGRXk1fUM17zKl209fsZt9NmXwNzKRZCZ5mLJiVCTfFQSnVJy7r6Tjwl7DhFxz8=,iv:9YZbAdUB9Wsy1Zp5KpVG2cgQdn/AQCXQWfQS4qlitdg=,tag:ADkgPprhvbfjI5XfqoethA==,type:str]
    version: 3.13.2
