apiVersion: v1
kind: Service
metadata:
  name: piper
  namespace: voice
  labels:
    app.kubernetes.io/name: piper
    app.kubernetes.io/component: tts
spec:
  type: ClusterIP
  ports:
    - name: wyoming
      port: 10200
      targetPort: wyoming
      protocol: TCP
  selector:
    app.kubernetes.io/name: piper
