apiVersion: v1
kind: Service
metadata:
  name: whisper
  namespace: voice
  labels:
    app.kubernetes.io/name: whisper
    app.kubernetes.io/component: stt
spec:
  type: ClusterIP
  ports:
    - name: wyoming
      port: 10300
      targetPort: wyoming
      protocol: TCP
  selector:
    app.kubernetes.io/name: whisper
