clusterName: homme-cluster
talosVersion: v1.13.6
kubernetesVersion: v1.36.0
endpoint: https://${TALOS_VIP}:6443
allowSchedulingOnMasters: true
cniConfig:
  name: none

nodes:
  - hostname: ser-msa2cp1
    ipAddress: ${TALOS_NODE_CP1_IP}
    controlPlane: true
    installDiskSelector:
      model: "FORESEE*"
    networkInterfaces:
      - interface: enp5s0f0np0
        dhcp: true
        addresses:
          - ${TALOS_NODE_CP1_IP}/16
        vip:
          ip: ${TALOS_VIP}
    schematic:
      customization:
        systemExtensions:
          officialExtensions:
            - siderolabs/amd-ucode
            - siderolabs/amdgpu
            - siderolabs/iscsi-tools
            - siderolabs/util-linux-tools
            - siderolabs/nonfree-kmod-nvidia-lts
            - siderolabs/nvidia-container-toolkit-lts
    patches:
      - "@./patches/nodes/ser-msa2cp1-gpu.yaml"

  - hostname: ser-msa2cp2
    ipAddress: ${TALOS_NODE_CP2_IP}
    controlPlane: true
    installDiskSelector:
      model: "FORESEE*"
    networkInterfaces:
      - interface: enp5s0f0np0
        dhcp: true
        addresses:
          - ${TALOS_NODE_CP2_IP}/16
        vip:
          ip: ${TALOS_VIP}
    schematic:
      customization:
        systemExtensions:
          officialExtensions:
            - siderolabs/amd-ucode
            - siderolabs/amdgpu
            - siderolabs/iscsi-tools
            - siderolabs/util-linux-tools

  - hostname: ser-msa2cp3
    ipAddress: ${TALOS_NODE_CP3_IP}
    controlPlane: true
    installDiskSelector:
      model: "FORESEE*"
    networkInterfaces:
      - interface: enp5s0f0np0
        dhcp: true
        addresses:
          - ${TALOS_NODE_CP3_IP}/16
        vip:
          ip: ${TALOS_VIP}
    schematic:
      customization:
        systemExtensions:
          officialExtensions:
            - siderolabs/amd-ucode
            - siderolabs/amdgpu
            - siderolabs/iscsi-tools
            - siderolabs/util-linux-tools

  - hostname: ser-n100wk1
    ipAddress: ${TALOS_NODE_WK1_IP}
    controlPlane: false
    installDiskSelector:
      model: "VICKTER*"
    networkInterfaces:
      - interface: enp3s0
        dhcp: true
        addresses:
          - ${TALOS_NODE_WK1_IP}/16
    schematic:
      customization:
        systemExtensions:
          officialExtensions:
            - siderolabs/intel-ucode
            - siderolabs/i915
            - siderolabs/util-linux-tools
    patches:
      - "@./patches/nodes/ser-n100wk1-dedicated.yaml"

controlPlane:
  patches:
    - "@./patches/global/storage.yaml"
    - |-
      cluster:
        network:
          cni:
            name: none
        proxy:
          disabled: true
      machine:
        features:
          kubePrism:
            enabled: true
            port: 7445
        kubelet:
          extraArgs:
            rotate-server-certificates: "true"
        sysctls:
          vm.nr_hugepages: "1024"
        kernel:
          modules:
            - name: nvme_tcp
            - name: vfio_pci
            - name: vfio_iommu_type1
            - name: uio_pci_generic
            - name: ublk_drv
