clusterName: homme-cluster
talosVersion: v1.13.6
kubernetesVersion: v1.36.0
endpoint: https://192.0.2.1:6443
allowSchedulingOnMasters: true
cniConfig:
  name: none

nodes:
  - hostname: ser-msa2cp1
    ipAddress: 192.0.2.2
    controlPlane: true
    installDiskSelector:
      model: "FORESEE*"
    networkInterfaces:
      - interface: enp5s0f0np0
        dhcp: true
        addresses:
          - 192.0.2.2/16
        vip:
          ip: 192.0.2.1
    schematic:
      customization:
        systemExtensions:
          officialExtensions:
            - siderolabs/amd-ucode
            - siderolabs/amdgpu
            - siderolabs/iscsi-tools
            - siderolabs/util-linux-tools
            # - siderolabs/nonfree-kmod-nvidia-lts
            # - siderolabs/nvidia-container-toolkit-lts
    # patches:
    #   - "@./patches/nodes/ser-msa2cp1-gpu.yaml"

  - hostname: ser-msa2cp2
    ipAddress: 192.0.2.3
    controlPlane: true
    installDiskSelector:
      model: "FORESEE*"
    networkInterfaces:
      - interface: enp5s0f0np0
        dhcp: true
        addresses:
          - 192.0.2.3/16
        vip:
          ip: 192.0.2.1
    schematic:
      customization:
        systemExtensions:
          officialExtensions:
            - siderolabs/amd-ucode
            - siderolabs/amdgpu
            - siderolabs/iscsi-tools
            - siderolabs/util-linux-tools

  - hostname: ser-msa2cp3
    ipAddress: 192.0.2.4
    controlPlane: true
    installDiskSelector:
      model: "FORESEE*"
    networkInterfaces:
      - interface: enp5s0f0np0
        dhcp: true
        addresses:
          - 192.0.2.4/16
        vip:
          ip: 192.0.2.1
    schematic:
      customization:
        systemExtensions:
          officialExtensions:
            - siderolabs/amd-ucode
            - siderolabs/amdgpu
            - siderolabs/iscsi-tools
            - siderolabs/util-linux-tools

controlPlane:
  patches:
    - "@./patches/global/storage.yaml"
    - |-
      cluster:
        network:
          cni:
            name: none
        proxy:
          disabled: true
      machine:
        features:
          kubePrism:
            enabled: true
            port: 7445
        sysctls:
          vm.nr_hugepages: "1024"
        kernel:
          modules:
            - name: nvme_tcp
            - name: vfio_pci
            - name: vfio_iommu_type1
            - name: uio_pci_generic
            - name: ublk_drv
