apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ntfy
resources:
  - namespace.yaml
  - pvc-cache.yaml
  - pvc-auth.yaml
  - deployment.yaml
  - service.yaml
  - httproute.yaml
