apiVersion: v1
kind: Secret
metadata:
    name: ha-mcp-secret
    namespace: ha-mcp
    labels:
        app.kubernetes.io/name: ha-mcp
type: Opaque
stringData:
    HOMEASSISTANT_TOKEN: ENC[AES256_GCM,data:pIj4kL9h66eYwLaZ4i8yO2nj0CeAh7+iJCPdO7J5ku4J8W7507ma8qFqfGBZVsGdg3Vigpq3p+Ji+C/W/jil7rgRs67h8/haf6Py2enP/JL4FKIrhN35L1yFt5GiYXRZOu++Lf0PNlBs9gud8RhtQjv0Bhtiy+UF3MxiSUfzcFArXyR1i5bMTK+QETdvcs3RHs9ukYUHTlTnIqrm8gNhuD7YU/CUQKiwrQBSN0YTK2PseBH3PRwm,iv:sS6/9OMJxNCkmWqQmSt2RJ4zZPj8jzerUxvKKY60sO0=,tag:Q0tOhR0yXz5Ao6QkAg7pRQ==,type:str]
    OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:/X3wLk497ROq/Plt98YQaPnr7GCRvsDh+V8FXfOY+MllMm9Jk7gRYzSjQPrKtQAtl4kFvkYAYg018jlyhmVS0A==,iv:PmA0L221/pGyjMxkSAPlJXMg4eplvdmqLQnchXmO2hI=,tag:vmWPYrQ0P5PhFxfN2AplDw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3cFllUUFid1NnY2I0RGdm
            c2hXaTNVUDc2T2FqNGtOZGQ2R1VNNDE2T1FNCnZnT0lmb3lLOUwwSEVSaHdFQTJ6
            dmZHUTY4LzBMTVNVMWdlSHN5WWZVdTgKLS0tIDlFTTB3clIyTm1TYlJOM0kvZEJZ
            S2hEUEZ3YWN0RUIrTXNla09qNkljQ1kKE7tvQDUc7eu+fHu24KGf8h1HHyGEGvgs
            JemyFiyUk4r/xEgHYrV2Sw2l2TwiKI32vAUZuwW3dsefGOEiisJ5gQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1j6zlq24dlzd9as6gq835980ahzelmnuu7d8ydkz54t28kzhv0csse96epz
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-05T01:24:40Z"
    mac: ENC[AES256_GCM,data:9HqkDebw4pQZnIMgKO4UjBBBlr8CtxzXxJHQDUjnTTfGiTBHDCr1H2nIK+vEP63rs1iRkWZ7qN+71asjI1Nw0zPcHYxAhbfhvjUVmjB5BD+8/Qb2+ZHpAX7yshssXrUGkT2H0ZDdulwRNEA6IF40YGwitwQZZEvinKTTwtfhETo=,iv:RFUVlVwuFptmJIwnYDK/qzuUA7XmnKEZs4lv6P3wTpM=,tag:A/SsjVIOu37ib2lFFiyocA==,type:str]
    version: 3.13.2
