apiVersion: ENC[AES256_GCM,data:8bI=,iv:Q3NEN7S7kGXVXBi65dsRHwoRW1EnGo15NdbeyzNnu30=,tag:Rlzyv1VPQ0Ke8/0qaSmEWQ==,type:str]
kind: ENC[AES256_GCM,data:xJYjsQJi,iv:qfRkNClrhfsc127ImkjbO1WAl0AR5El1gFThFun6xSI=,tag:ayP87L1SDpEXE2PoUGAtlA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:9HeDIn8W2TvnBZ8Rodo8G42dHXIvOWrU,iv:6SxsC5EwdbIh3NM+9GhIB12t5R+rDQB2Tah6GZJAvu0=,tag:FpCBTGYu+adEYe13pcx68Q==,type:str]
    namespace: ENC[AES256_GCM,data:znwy3nsa4dA=,iv:V+/g/aWwSvHC7LqtNh7G67E59JqiIN3OctaveYcOd78=,tag:zPzyX9phuCYysh2g08xLLw==,type:str]
type: ENC[AES256_GCM,data:f5B2nSmJ5NmyeemTenSC6hMcLz9PfxKd,iv:4RxRRxKsy1zJ3EseHQ6jQh8gwwJqh0x5KrikSeLePSY=,tag:nYq0wokZacH0fi+cj2E48A==,type:str]
stringData:
    username: ENC[AES256_GCM,data:GRmxpKn8xqw=,iv:cW4WUcbpGt8+UsqqJYXgilClCnPBjeGHfa0cVEK10RI=,tag:wnF/hbf2TEk4jcwqwX3m2g==,type:str]
    password: ENC[AES256_GCM,data:ktqsn3eNuuXkOKKmx8oADb3LcG2ojGueHunfVA/qSY0=,iv:NcCMVMzd8/2rDd8IRl3WRWFXBZP90dxgNI3+I8LCuq0=,tag:4VmSXN+5qGWiNgNl0uwq0Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLOE1mYnBGVzJSOXlpWENv
            SFo1bmZlWXRpU2FBdHlObzYwZlFmMGpVRVVFCkQ5RlhJbWptRXdEbWlKQzU3eDYr
            ZzZzSStkWjhpcUlmd1Q2NUhNVXIreDQKLS0tIHdDRVZwWlhYcGFrWnl1cnRRYkRI
            UWFQOEpaUHlpeitLQzdTcXV3UWVHTm8K8X52ef7qxfci3Pp4q7M6bzxB/8uz6v2f
            zHXdT7lPy6Rkwz0z21O6F7VjfR71Mcda7vRpj5yLkqtqgc1RQEK0Hg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1j6zlq24dlzd9as6gq835980ahzelmnuu7d8ydkz54t28kzhv0csse96epz
    lastmodified: "2026-07-20T02:38:47Z"
    mac: ENC[AES256_GCM,data:gLzFR7FGbHjQEzVqJ9ZxKSS/CWrs+YZxhdtqiXsmUZIF7lbljogexUjIH7pn5zRNZSJGXEjrpeJWd4qGB9Z4MqC3ak734qn2R238r5HVseyx+KxqB3+Gi0M3wl2iGLsFFBAocpnJV+PqoF0zawaVDtwjZtArbhgZUML5cl0sYCw=,iv:rXs5NrQ8Ib1sdQ69Cm6f3El0rzXj/s9e3NfQlvjnNJ4=,tag:Fu7lrMCnKwOIzgX3G/gfUg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
