apiVersion: ENC[AES256_GCM,data:TGo=,iv:lB/nRTw5Zb89mmIfznjfOolQNmUs7ijDZ8rjfMEVZtE=,tag:0uE6kdIqUrQVt6yD2loCWQ==,type:str]
kind: ENC[AES256_GCM,data:RUVU8izd,iv:1gjGOzG/M4uYkGA66e/5ozxRwWsZZQ2eouxi/uH274s=,tag:cy8QCs/e7ibQm+8dX0KlXA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:D6PaIaUqFd5s+j3UahvhguWT,iv:zX4qEUb0EnRJ4/WxLmWGWup0fG6xDV5N57wJglbJesc=,tag:UbR8EIpXV0SRu7AAK6kNqQ==,type:str]
    namespace: ENC[AES256_GCM,data:u+HKOVGIAxs=,iv:EvAut0X63dI06SpQ3ULGiI947vEq+pk6HqnFlv4ZBC0=,tag:JdEVDq2OMw0KmG39DX9T6g==,type:str]
type: ENC[AES256_GCM,data:0zYk7uXc,iv:5oW9IGnBdQJ0KU/COdYZid58hQpt75fW8XBHPEUO0gI=,tag:9kXStxV+rAaqFvqu/AWI6w==,type:str]
stringData:
    #ENC[AES256_GCM,data:Jz9R5Wj7Oy9Nry26fp0HRPi4xfu91AN9EJvRtDXv8TVZWrPVYNfqhML+AzfIj07Z9KFChdxtYoyOu/DZq3gzglA2V0a64Ak=,iv:Bj5x0wZFipyukyiYQmbajvOObMDGHnNCSzcZXw1/V3w=,tag:Q5iGiG/qromlWDZDar7IKA==,type:comment]
    ACCESS_KEY_ID: ENC[AES256_GCM,data:9SyX9A+n/ehqtG5VKCEebF3hUFQ+QzzT7ZZXGvEpuks=,iv:9bSeP5dZpu4635y1I5FiRcPf9M/dIkSwx00jaOpLew4=,tag:XKFX4jWaeHA64dOcESid2g==,type:str]
    SECRET_ACCESS_KEY: ENC[AES256_GCM,data:rOZr8mqZOVm3SatRi5yU5Mtiayn9dOZaR1jHG7K19g6WrbvQylDqkg==,iv:R/W42qNv+ayzSRWakOvUm96L8XCrCnRM6jVTc4/cfqM=,tag:NnbeRR1qwrRwcaKPzAV6PQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3c0VGNTRyS29zTXBBdHJN
            Z0U4RHBUV2pXTUY2a0xydEVhZFRLeCttN2xBCjE0WEVFZURqUmI4bHU1Q3Q0Z3NO
            Ny9QR3hSYkNWNHBtbmZqa1BuTkhyR1kKLS0tIG1ZbjZicEtDbEpZVmdaQlBJNGJz
            aUU1YjF1NzRsVUpmYVl6Mjg5TlpBdkUKmpFjxlkxAHix5YgoBW84m8esBHJO5sX5
            zSyq8d7Of19HZYo0vphazK0UhDVk84XMO+obngXo435JIvO1CIgiIA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1j6zlq24dlzd9as6gq835980ahzelmnuu7d8ydkz54t28kzhv0csse96epz
    lastmodified: "2026-07-25T18:23:01Z"
    mac: ENC[AES256_GCM,data:RtyucpzWBe85+kJC3QQu6x+W2ZIp7lx58kyGVeuwaxmUW3ijwNMAPNsROyLQrvqKdeWnNNxLxDC4FchKObGvfSOV6v4XB83x/mELAe0A54BHuHBOVfXxLhKuLpHYsdZq8ooH5jBFcVTs6I3jWkOuzxXDvpazk2/KdoWxr33tnzU=,iv:d9cVPlGaqocTggyfoDbGGkZUQ6deFsg2AR0ZdsAUkFE=,tag:G1S0O3OjWLJeIiHi5jWfZw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
