apiVersion: ENC[AES256_GCM,data:Qv0=,iv:bnRSKvdCarypPGgdbfBSpkofuHiT1S8v6Agq1491RoM=,tag:Aq5TSCARQNEM3CO3OIPEhg==,type:str]
kind: ENC[AES256_GCM,data:SIwVoSOW,iv:epPFnlTAskemR0TenxgzWf6noizOWjk6j5v/npkhQ3w=,tag:a1iGwS1ltkrssqFwMt6e7w==,type:str]
metadata:
    name: ENC[AES256_GCM,data:1iuNNBb9AqBwzct+6dA78B0oC1E7gMbDZxbVFpbC,iv:DKOssJ/CbIjRe8q18uYTUNzFy5g6gixHpLNP4yXf490=,tag:MGVa2MO8MVc+VF+qIxGb8Q==,type:str]
    namespace: ENC[AES256_GCM,data:72l9ETyBu7g=,iv:O4XTSiw7h09mvXTG4UQThGNzEWne/WbLfa0jwJZ8R60=,tag:HaTC7h1jVbSs6IZUpkoWtA==,type:str]
type: ENC[AES256_GCM,data:EBBfs5WDNdZePNxWLdKzaYhyIf+0tntV,iv:L+p62bCS+77VwX88ivZdxsAK/MMZ6jfcEA3BPqNv6VA=,tag:5rFKWllbA2WUPw7ebaHdng==,type:str]
stringData:
    username: ENC[AES256_GCM,data:4VeQqUhiCOMfNbc2sw==,iv:AdgWkLSHHvl3ZbOG4dtyJ8QJ+ZlXD6TUtuCdCVjqfqI=,tag:ZCxhzCHHzlzp8ZSrGHMw/g==,type:str]
    password: ENC[AES256_GCM,data:fgqZDWnOVTP/ckMztyqeLxiY4QYKw2NZwU36yMZd2ruQ6krCSv4m7Q==,iv:ZWNLSjFkn685JMhFO+TUZcoj7TZvvg3oJX5BId50y3E=,tag:G5Wx9+xr5tOJagOlzs+1cw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFbUJRM0ZJMTNBYnltVFJj
            ZldMQTF0UzRtVmlSTW9uVHo3QWEvQ0YvT1F3Ck5rWHBDNVZZOEpQVUJleTREelBw
            NlRvbnRpVVY5RlRzNW1mV0h2N2g1aWsKLS0tIGFKNXBsMEhyRWZYR1ltdjFOWTh0
            YXphRURxY3FENGRnRG1Sb09Rd1cxTHcKTGMCPWW8vGpWhRqTKm7MotAXcJwegtC+
            bXoEi9y3FqWPG0oLrA+YpNyIeu7iER46lAZ0S8tKPa5/s24o2zpkoQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1j6zlq24dlzd9as6gq835980ahzelmnuu7d8ydkz54t28kzhv0csse96epz
    lastmodified: "2026-07-20T22:16:05Z"
    mac: ENC[AES256_GCM,data:selulJZVWj5eUK8rlHmwPvbCDFthTrRthHoRsVpEZCf0iWB+RIrHPyvTMSBYimIyiLvrt/Ybi+XxLcrDiTeJ58QrP6FG09sqDO1RhmQnSntXcCavkONigNc6MlXTSjJZP+H5qw9FDTCEfOB66Jx659DScVYVrdFWYSC23sxpvGc=,iv:0Dkb+HyIXSW+NtNuxO3pcNqYHWpsZpDIPoSNnMIo9KU=,tag:em4teev0R5aoDJeQr1yb/A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
