apiVersion: v1
kind: Secret
metadata:
    name: homebox-postgres-secret
    namespace: postgres
type: Opaque
stringData:
    #ENC[AES256_GCM,data:D68CjLfmR9405hxzW3IiSs8eLkPkjM/vOy8thEZ3FPjsnjKsaoHlXqqIsUdTeRB7mLNls+nfjKSKwpOQsBC9,iv:E/mflrfNyTw3nGzJoVqTqjhskLdhrKpc1gWb9AeEDJw=,tag:g5RiJh3I4rOQOKvePWKGVg==,type:comment]
    username: ENC[AES256_GCM,data:HzSi32VyxA==,iv:oNNKu5MUZtBanGIhJdnrKldMQVxjgT9mf9AErhUet7E=,tag:Hd6NU2ql4RLdQZOi2H7UwA==,type:str]
    password: ENC[AES256_GCM,data:1iIsRSLvyZvF7lDZ81I6aYUivF0CaMtRyjERxb9AeEotLxyxjejjvA==,iv:zEgee+RN33nisM+RnieDBg8+y80WlSnerCYSkAcianA=,tag:Z/PZposTqwzM+DJo2nDh+Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnUElxK2IwT0lmRDRmWHRN
            YkdpUmpySi8xd1dXclhHMGVqWWdjdmxMK1hFClV5N2dZME1PWnhGQTV6cVM0UGVW
            N1hYQWRPdDdvSnlqVTQwVTY1Y3p6RjQKLS0tIGMvOHcrblRldTZzY0VQWHdoVUlK
            NmJMKzRncGhtYTFTUVZCT1liMXE5cW8KqYzhM7RXBifBUTcEoXwwQfH8lO5Lfzds
            ednnfnK0tztK3dc23omOr+dRzTvjBXXDvyhJywdgila+eQIEA8yJMQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1j6zlq24dlzd9as6gq835980ahzelmnuu7d8ydkz54t28kzhv0csse96epz
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-19T20:13:23Z"
    mac: ENC[AES256_GCM,data:Wb111EZFskEJEFAnpNeLbctvSSwxUk8/rXWKxs9STqVJ7mbBzrytkkM7SIXZq83y0hVlOw/vOcPR+zigDCzwlVwLBHOu1kMKEzzzN4voI3+cOjCMPVgEIm5cKwdU8T6DwAnJdy/nGKKMW/rxzECdp3/yyqpIcgXsuM9/QpYBJNA=,iv:rjcjxvo2RkriVpoxEyBe6xlt0/v3khKhokfv+tly4RQ=,tag:X315Kb8i8Bak/2xi27QJ5Q==,type:str]
    version: 3.13.2
