apiVersion: ENC[AES256_GCM,data:ank=,iv:eXYtEMGVXXmHzm8ZwrITtmf+0EtVdyoNOhGSody2dsg=,tag:SBy1TiHd1p516eTfyIefVw==,type:str]
kind: ENC[AES256_GCM,data:7wKfreHu,iv:VIiY2ardQrrwpuyTqM79/nYabVESzNv8BnDcX7sW240=,tag:sAkYQMHw/ILE+/2rw6zTNw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:PtEmsPZxFcbRSmPokOkEJWuTlA==,iv:qVfSPhlS9InfRSs2J2BxGBLoMrLgOxrp/dT2GP1zKrY=,tag:WzHwtSbpFtvU4d9jmJ5s0Q==,type:str]
    namespace: ENC[AES256_GCM,data:HIGT4a99VTc=,iv:4OFzP9Eqv2fWFfi79/vCkGxaX3DU1d1UJRqIPMwRhfU=,tag:Wm5XTA943s0fkkf66xC+Rg==,type:str]
type: ENC[AES256_GCM,data:GpZ41AC/,iv:FyUF2Ltp47jKYw2a9tiheSJ70clua//mSB+E8EmmHEc=,tag:68X4CRwxrhyDDleKFU0t9Q==,type:str]
stringData:
    #ENC[AES256_GCM,data:mBA3nRtdATmhYOB6/fTcYMh19YEqfc0fWqBDiHL7So7MFdjUUtmALQYC5N1lt7x394TILEp6OisHF1U=,iv:WgFAfZnjnec0mJrKh33YjC1B/Bgv1uojbZ7U5vUK8/I=,tag:W+g7O6tJtuOZveL4SH0Z5Q==,type:comment]
    #ENC[AES256_GCM,data:FH9hDqRWbM0FqWuqjYLga0mhhXSBnU+cyrqNY0So4TV5+J1X/yKLdqolXoD7M4tuXWNTPcg6OMuFf/MflcNf25N+k/VuJSP16mw5nGE3KlP0gbU=,iv:iBw2SpYhx+9iJZIblvR6DineFdat4ajk22RimiJuVqQ=,tag:iUQN2yotg4YyVqqofmouzQ==,type:comment]
    username: ENC[AES256_GCM,data:OZLQ,iv:NILF8wnFXd9jFPcdNy5yOMsw0VzroYryayCnXJ8YjwU=,tag:RtDgwMshAywZ3XojpoRtvg==,type:str]
    password: ENC[AES256_GCM,data:ey5liVfieGZ+7fj34KQ=,iv:biIzGft2BzMAQLr9ImzXT3aMCRgDFZNUO5Hm4IF1SjA=,tag:ojAZktwAuIAs0CP6/jS1Hw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAySlNkMVVuUndnbEkxMEZp
            S0VOdDFNQlJyaXZRcjJ3RmlPM1ZuM1FTaFZZCnlCNDBGVzZTQmdKZExKVlRLby95
            eXBFaGJPNGl1bXdoZUpBOURFbHhFbFUKLS0tIDN2T2Nza0liL0hrNmcvU0F3dTUz
            cVp6TVBuRzViMG1ieUhJWGFKVW9XZTQKlyuDdYL0CibEmXQ2p7gnt0cAAfxMGkuw
            1eRu3iVa56ZOLkcllZU97c9tlxkP/AvQ7Mk1e0aQSAWKt53cIl5e0w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1j6zlq24dlzd9as6gq835980ahzelmnuu7d8ydkz54t28kzhv0csse96epz
    lastmodified: "2026-07-22T20:22:12Z"
    mac: ENC[AES256_GCM,data:fz8ZXLrJ3AaSttlbTkfCGowBi6pMBnmPKQHOPxCgLko4cnt0UW6urUJzeB1IZL3idoYCmB9IS4jM8P8fb1pyMSxRVB/53fU8lKIh8Eh5jJebvy5qT5LwY+DlYJ6gBnqLbR9nGaYkduTsLPgU5Hth3tYtdhsd+jIWfxRZhaZemeg=,iv:4MeLLj8ob7Y/MBMIkpJ4cyExldu+eQd3lytewGQdEBQ=,tag:lIUbfQPik5vAvIXxW6SZuA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
