apiVersion: ENC[AES256_GCM,data:P54=,iv:vDfzlZTBOaxYsjhdZQFL4bwCnbIZEa2ntJMAg4DWyFY=,tag:TAi+0FRuY7trPjAmGVC8lQ==,type:str]
kind: ENC[AES256_GCM,data:hBHfE/ON,iv:CwWG+BEKvTa5lPNhzvpSRjLwlfx6xJNG0+p04gQCchY=,tag:z/jjNERxxpGDWc/0PQ83fg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:ZrSKOC70suce3t8mebU5mC6VkgbKfLk5Pw==,iv:4xHlnb47TRrReErDGQWOB7eANhYGrsX5bRM28mvDb68=,tag:SHYuXbKh76eamFtKhZABnA==,type:str]
    namespace: ENC[AES256_GCM,data:BFUe478lBTg=,iv:f0xooQwiJ3foBx4iDmcVCZTXixrns0Des4thjN6FUao=,tag:pQKn10vUCY0a6g7+qrKOpQ==,type:str]
type: ENC[AES256_GCM,data:UrDQG1gRxcu9VvCvui4q4aTMbl/VIoJy,iv:0NYGGDbaXBTIDYakG8RIv9Mwbe6R4APvj7Oy/q/MaTA=,tag:aW6VVFhUQRGyu1uPTsDAdA==,type:str]
stringData:
    username: ENC[AES256_GCM,data:0O3aA4BIko4=,iv:O2bwL8Lv/Z9T9WaqMBn9KZ95usAhFusQgbPqrvVLzww=,tag:fh1Kv4bn6lqATwfJEEZl2Q==,type:str]
    password: ENC[AES256_GCM,data:sCNrtzchPXWCllDVG/KSTmLbiFaWyAwa,iv:uWim0/zsfGCz5feAWMx4c3zlzEyMIDVXk1gni1Uv/Mg=,tag:HPCX/JTpKIFBrS2Qp8GrFQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArV0g4cGpvTGsrQWVuZDJN
            U3hiZ21xRzRXR3NUeHpVSUNrYnhvSW9pb0V3CnV0V2lrUnZyT2N0N1pRc2RGV2sr
            cGJTZ3VsblQrUDhFakUyN1NnZDFENkEKLS0tIDJGdytEUnlIc1hlMGJHWUN1NE9U
            NmFGbGgyS2N5MlZQV0JLTnJ1S1d2S0EK0ib3APshr5nzxYg5e0wyvNWBbiWWBARK
            aLmAxR1iamSKKlZmUA22O73becCTGlCxq3LD1KfE1v5stynE3ajRYA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1j6zlq24dlzd9as6gq835980ahzelmnuu7d8ydkz54t28kzhv0csse96epz
    lastmodified: "2026-07-20T02:06:45Z"
    mac: ENC[AES256_GCM,data:mFoD/EF9FcQLfO+Mhe5nhdxjWUqQzHmfq/RX4VrvCaDAaXAbN0DFrLEfRiygmTX2pgW450P0atP2prcgEml7q2tJQUHx5K5I42Y0qUhXWsoLj2OUQBbUIDaNX6PHSFOPihAcED4fDZI/c1WFQEOoI+0yGDgXqA40uZdMop/RN4I=,iv:AUIK9xPSO10hrgH8dAgxiBsD6UsVHszf68zhnzLSPko=,tag:JCU92y/PnJMWq+yeR70Djw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
