apiVersion: ENC[AES256_GCM,data:pZY=,iv:mZEpeynifFQR6FMTNvcX1BDaHvKfUBSZVaYlt/stjrk=,tag:AioihJcn12YDPRaDR+rTKg==,type:str]
kind: ENC[AES256_GCM,data:C30lGu/v,iv:KMiitu5d9khJyljOcGODOVw+abUvd5IdRDXILBAYAdo=,tag:YBzIZ+j2JdTTsx44YI7ZHQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:Bj6HrC5LVgKXf6f7AdkmRtM=,iv:sWqEmQMo3O+NXDOxH8VNl1VGoRhN4oOKup97B6IRw7I=,tag:eCGKVoBKVclgsLorPLcmuw==,type:str]
    namespace: ENC[AES256_GCM,data:j1ykVrlaTYUP9uw=,iv:4350HS2sHLU5zS09bmHaP/xbcDByy52mDx+3p45wjAI=,tag:gIwFOV1sgfLy843tmZdLOA==,type:str]
type: ENC[AES256_GCM,data:nKUxyORU,iv:i878HaU/qdmZ1FxOaN1CO4JjzWHpVHpxDrAnDH6ml38=,tag:U0lWJ/BIDctoMw13e7QYsQ==,type:str]
stringData:
    ADMIN_TOKEN: ENC[AES256_GCM,data:VL/1gbFpHEiUE3R1iBKokWZ2GlPtFLk19cAG7akfDjjbLFNeCd6qvEfxVlz+vIu6PgDt32o84NkIOLduTTAmu+36sZRQejRDPlvT07QtVsgwElwVBWEcmF0Xp4jrZjJT0xE8PqfRo37zeMViwspS+ykWFhAX0w==,iv:aVDW0ufHjMJ6zgzdoXSDldOx4vRmZ/hnXEjn3P03Vko=,tag:hfiMhNveke00qM7bP/xk1Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1ZElEWXJ6KzFldHRadnNW
            TWozZERJY01SaGs2dUlnbEVMcHFWOW5KaEg0CkVZMEIzMlNhZkNpZlFqT1VsN3hI
            eVNrYkpERnBESUF3SDN3Mnl4eTVJbDQKLS0tIHh2OXoxZDBDdUdNM2JEV210eGFM
            UkpFMW8vNW5wUURFTC9sT3VhUXVtRnMKhkXE85N//8ujwpugnVdwC4VAvHzftqWa
            APd4aE+51bNkBsWXgTQujjMvBEMOS3X2ryGr4/wgO8FD8uIKfgqwqQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1j6zlq24dlzd9as6gq835980ahzelmnuu7d8ydkz54t28kzhv0csse96epz
    lastmodified: "2026-07-22T13:51:59Z"
    mac: ENC[AES256_GCM,data:eB70Ka77+RAv42hHSO8njQLZir65LFZFIyDy8k99TubsfNJsFCjlvajI4jjV2iPG4m9T7htex+pHml7TNhAOqpzkJGjWoo6NB2LPxt50axBdFyoSzX00vRGwc6RW9JG1UkMECwQ2K+w9lfzjtgIP2l+pdkJQ4hyWW8k3BTAd9/Q=,iv:EKk2etRFOMDgAbWGEqDDKCugvipSBhm9pPr+aCo7HjU=,tag:+vWizz5LTO1wCXcIh65QvQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
