apiVersion: ENC[AES256_GCM,data:XgM=,iv:55SRm8YKSY6DlGlRK5cHS6/NisI/ZkiOSRWn9IGytA0=,tag:ItFEy/bpAEpRUMr2ee5aWA==,type:str]
kind: ENC[AES256_GCM,data:K2aDz2sS,iv:4Evi6AvdJCrPEFRS0vWDGfe6KiO+1NEH3dv7GZsGGKI=,tag:sy5dgMFuFUu1GMYHYIqHRw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:k6CUFDsb+laO0g==,iv:zohPJibNfim7Hj2RLk3tAiPP93H2lRFp4mjbC8UbjL8=,tag:VFErlrm3Rn3GeZVEhim5sQ==,type:str]
    namespace: ENC[AES256_GCM,data:dXSN,iv:M8Kr4l3KzASfv2z1JvbEfAwg7h/xLsKlXy6Io6bYG1I=,tag:sexK7iKfL1/txVKYujwAkQ==,type:str]
type: ENC[AES256_GCM,data:btM/3Njz,iv:Iz6A/s8y1FhhDfC1xgbiZoaAFox3b/rMnHpPgiEw7qU=,tag:DM7OtfZ3sY45IvXKsOwLJw==,type:str]
stringData:
    #ENC[AES256_GCM,data:CRzw3Zh+fDsiGnopkr2gY/zrXdVE660SwO5J5TdJcX+n4A2afAtF9jVTK+dVfBnnS/Bl418VTS5ihNEJaRhUHP8=,iv:kZ/KT139cw04Tdguzg5E5G8c33+0PoHIR8/EkfNHK5E=,tag:spQ7gayMaejH4AToqwkhTA==,type:comment]
    #ENC[AES256_GCM,data:lbEB8BD9njc5pja0y8NNiPlvqaqEc4OwNOMliwwcZltzslFFTaGB/KJOeLfdZ8Hqy4HOGpXXoacDnPAOQG5YQnO1KIhbQwTNHd2H/CwOBoI=,iv:/PmDnA63mx3gPuwqZH1xsqsudGTo2VBu4JvhMQp76KQ=,tag:SwdcWLDrX+Q/dUycZpz7WA==,type:comment]
    DB_POSTGRESDB_PASSWORD: ENC[AES256_GCM,data:D3nJinvgFGRFX4bd++c=,iv:lDX7clL+vBycQaZvqmygMcb5OPaB+NE52Z5X7/yelaY=,tag:KMxR5tY5wEnkxsa/dhqE/Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBscEZCUUx5T3djRDl5enFY
            N244UkJicGt0WUl2ZGJ2TWZuSVpwa2phZUJZCnZCUTNPcWtaZm84ZDBOREM2MWF0
            ZzRWelRGQnBxVGdodHNPRUoyejdqTTgKLS0tIHFNK3RTNSt6S2ZEZE1na3hST3V3
            dDh4MG11R1lwcE1uMGRyUVArU3ljSkUKBux+W8ba/aUpQr1+ub2Hc+tth+Fw9eFq
            T1EkotNTQzIuVhwjGvRBsEExXmm9svLuSI7bXeqkodJzb0V4uzcngQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1j6zlq24dlzd9as6gq835980ahzelmnuu7d8ydkz54t28kzhv0csse96epz
    lastmodified: "2026-07-22T20:22:12Z"
    mac: ENC[AES256_GCM,data:hG3aYClNxTFr5LUg1cz+8LJ2TrwabDDJpq8ljAXvZ2IIetKl6eFgm1BiTxzD+4PS9l7GGHKN2lEOlEf3yECIp+janYLTTySoCtVjR3q8zNzwkkj72XEWTs+QNnCh/eNv3C6ZbGsEwzA8kpzAN2RTJs5Zds8mSxz7mtTQCRYCv+k=,iv:dEwAdG/8hFF9bZ0d592QraZLw/LOzKCflIRNhvRI8Ac=,tag:dFRSl3F8lOCzPdvl+j08LQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
