apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - bazarr
  - jellyfin
  - lidarr
  - maintainerr
  - prowlarr
  - radarr
  - sabnzbd
  - seerr
  - sonarr
  - subarr
  - subgen
