apiVersion: ENC[AES256_GCM,data:Vu0=,iv:X4OkVemSoZw4e9WlS01Cc4nTBoeEBUMpC/t+i5h/UO8=,tag:ZaCVlqVJyD1RkKzsNE9DeA==,type:str]
kind: ENC[AES256_GCM,data:ZVISADcC,iv:mJ66GfJPO657/FoM2OWPUVkmv/B+gJUStzKnpm7U9Uk=,tag:hSsu0HGW1O5n+EgWHANCVw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:EyzYo3ppfsLDlC+5kFQs,iv:Ii48PM63sUqlH6k0WpzW/uZc1RgdQQ/f3/r8dI6tOXY=,tag:gXMzC8Wk3l5uxgdTFV8meQ==,type:str]
    namespace: ENC[AES256_GCM,data:viAvSUxROAs=,iv:yHi6A5oBy3yxNvUik5SctltlDxYHOGEivw7P36o2etw=,tag:uit+B+IKVMRUFNytWMVOAA==,type:str]
    labels:
        app.kubernetes.io/name: ENC[AES256_GCM,data:JI8h+WjABhE=,iv:phW9YYFdkOIlyvaF8PbHtfqJOfIQmo0vK3W/hw4MpGo=,tag:ia9Waq7FvN/OogKT2DIHVA==,type:str]
type: ENC[AES256_GCM,data:Hi1d7EOZ,iv:wsu20W4ves+2XPD4366kZe7tVFVoPGV1+yOxC0b8C5Q=,tag:zQB+TEr2XjDd5kop7pJk+w==,type:str]
stringData:
    HOMEPAGE_VAR_JELLYFIN_API_KEY: ENC[AES256_GCM,data:RL0ZirfgJ1TkjMPjGIO2NYmU4GfC6FQukKEcpagYsVE=,iv:v9a8ALiLAIBvma9RsUuCaU5fS9btB5og3a1jbOv9drU=,tag:kWYffUGepNJjVHKn7vITfg==,type:str]
    HOMEPAGE_VAR_JELLYSEERR_API_KEY: ENC[AES256_GCM,data:MGy0w0BWirXxQWMUfxBJ+90MKxQRyY2M2mwx04kIdC84UJIkM4pPaRET4+Fan63fUQx3MyAOlCDbrIs7cXrD7GAFzmg=,iv:VQsoHm12nCM/G92d1ef0Bro+b4SJI65K4ckNafBDI9k=,tag:rxkN7g2O8SOGbr5ITX2X3g==,type:str]
    HOMEPAGE_VAR_SONARR_API_KEY: ENC[AES256_GCM,data:tHHIkcWdiTc95PBuqo3LKzm6fLv7C+OZVc97qOrc2Hs=,iv:T1VQTBqF7gLoHbiNtdmuppP/FUTFdvJaC/5CPltJWqo=,tag:TYSvpIsmw7T/gn6OQP5Faw==,type:str]
    HOMEPAGE_VAR_RADARR_API_KEY: ENC[AES256_GCM,data:rXkxEcaXx7mz5Pe3l/r3XUuGKnZUDJ2xPgrD43pqDUM=,iv:PWh6UUVhVJc2ORskK0Z7YQL1RwKO5cY7qp4isLa3Kz4=,tag:vookdeJEXK4mi7ub5Ydq5Q==,type:str]
    HOMEPAGE_VAR_LIDARR_API_KEY: ENC[AES256_GCM,data:BaZWZOV5DjPUMQ8D0xtj8+At2UCGDqd9kMOu99NsPi4=,iv:OMYYOCAwOw679JgDGpdocO4/7OHrnQ8t4w/AD3E8OYg=,tag:9AS4o/MVQrc7qckKgcoU/w==,type:str]
    HOMEPAGE_VAR_BAZARR_API_KEY: ENC[AES256_GCM,data:W2klBD9HueRH/1MiMwZfq/yKqKTVdZ0Ps//lp9+q8mc=,iv:JtbsMnVwmeZ3UbZg4dLKbGtttCKiCNGnPu+smvOLUSU=,tag:6OJ+zf6gSW3o/OqT6BetQQ==,type:str]
    HOMEPAGE_VAR_PROWLARR_API_KEY: ENC[AES256_GCM,data:kDksG5u3N+xHWIrdGIUJV6SukyijcxPhvqU/4r5ErRk=,iv:nwrNj9rsUdvjKM4NgsnclA7oMtmYUrZXHXnMoXp1GUA=,tag:S8oCZw0MkJ7C09UkXgXjUA==,type:str]
    HOMEPAGE_VAR_SABNZBD_API_KEY: ENC[AES256_GCM,data:10edqlT1Iq8Jzgq9G/sjmmEjeMf7tkmFAX1lmrU+tqk=,iv:rXLazxis1nOWUCntyLj1LzGh8Qzg/itrlYU6mB8LatM=,tag:+KPzYZiCl8+MApRwpAoexg==,type:str]
    HOMEPAGE_VAR_HA_TOKEN: ENC[AES256_GCM,data:X/4oK/J7wER8JglmdEhkHp8wbg0KyPAOSV9Ymi8y4G4sXRQsG2rNybGuJ8hikv2KFxIiWpi3cmpdO45j9zGJBK4ziqdsZUsPmIZec8hZzj7uyn8tilCWP1ItnCY9rJ2pSMuHMObdVGlrz5iRKbvc9LdYcNUMrPU0zYSM0ERIpwdPEY3YDpEBhXQZm6JhM4EWn+A5AdEXnlsay1nrC0z7UrnCXFTQ8wk4gZ/uETt7Eawa5y8svQLO,iv:AsdMeW9Oa2DPaAz9SfvG7Hn4nvoLB2FU8yfAfOqUp34=,tag:AuRpx8nSMGDHn6j0hZ/PAw==,type:str]
    HOMEPAGE_VAR_UNIFI_USERNAME: ENC[AES256_GCM,data:TGVb8Qo=,iv:r7VVEKK3yzNf8DIjrz0AZdyNANdJqPPWqd8j9wygVJM=,tag:9yU7tw9mqT23x/FqI36zDg==,type:str]
    HOMEPAGE_VAR_UNIFI_PASSWORD: ENC[AES256_GCM,data:XP67/RyIybVXuakoXesnXOKlCDbhl08+,iv:6X+oTbe/MA6T76nifYSG18xmJipginW6AYpzUIVB61Q=,tag:vNDRmBcQ2RZuVwlaMV6y3Q==,type:str]
    HOMEPAGE_VAR_ADGUARD_USERNAME: ENC[AES256_GCM,data:pA3MD6E=,iv:ZTLrf4a7SbON4GAuj2eeLA/xeWo69Xm9HUYW+tO/vRk=,tag:G5ZPziqYwserH0X9k5VSJQ==,type:str]
    HOMEPAGE_VAR_ADGUARD_PASSWORD: ENC[AES256_GCM,data:aJNoo7uWns9ZBaiC9J08UUbjwdY=,iv:a6l/PPKRm7SCnOn5btEvuDo6kxZZC4zP+zK0h2A0BXU=,tag:FQIQ4Na7aAwFNrng0tBNGA==,type:str]
    HOMEPAGE_VAR_QNAP_USERNAME: ENC[AES256_GCM,data:jOgdD1n/sRksC1G/trc=,iv:Sid8SEW7g3NK314ROlKi18+uEMUDjx9CqJ1bn3etExk=,tag:dv4pLTmTdxzkbF35vO2s5A==,type:str]
    HOMEPAGE_VAR_QNAP_PASSWORD: ENC[AES256_GCM,data:cf8UVMcuniSTV+4Dcn5uVM0jqzczoRTv,iv:pN3yezf6xrgRvUqqkFaIQpq4jK/20VNjBtylU620B2E=,tag:ZMo2thHolH+QArkd2P20kA==,type:str]
    HOMEPAGE_VAR_GRAFANA_TOKEN: ENC[AES256_GCM,data:HiAvc0rA2dOYFz4AdJ79VteXpa3MMPhQrwFHF3NsqMn0a/sNHMgo8JsaPeYWmg==,iv:BqARTagLuRay5Z3z1rSNFoQ8RxiH+dxRQqBr6v8GNrY=,tag:NHzcz2WdMTjBY0UcgzcT6A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3cGVHSm00UjhHSTdyeTNs
            RWpmRGppdStVWVFJcEsvL1YrVnBNeHo2aXlNCmNVSEVKZEpIY3hYc3RiR1NtVThl
            RW5PZy9qV2YwNk1RV0Z1OGZpUFluWHMKLS0tIDAvS25OVTBsa0twa2tEanU0WEg4
            VWJnZXQ2MVNsYThidXJiTkhnK0Z5blUKCcsgW8tnlYjrYZsofYIvuBvlh9GQwKoR
            MSqDXASNEd7EMaeBVTsQSJaM/+MAcFkj3uQCTsXfGzxpxoX6SRNoCQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1j6zlq24dlzd9as6gq835980ahzelmnuu7d8ydkz54t28kzhv0csse96epz
    lastmodified: "2026-07-27T01:58:57Z"
    mac: ENC[AES256_GCM,data:c2p4q2KDO4+GBFp9qUkp7RGgYWD4rDg0Tw9lEue4c1DXVN5CK7G1ubaxNP3RfZT530gQwUdv/2IZAecF2Iqy0JE8Naisb/NwPeywYMQo7KO2BPxeWPewWD8qlbuPq/UEiT9B5T8eDCJ7N5G7/2HMwXZGwoTMjnaanPJVtrVuOqg=,iv:6arDtbdRZ9N+1LAFoM3aFyVIhP9lZVvU3KEiOyI9Ffs=,tag:f3BwjNaNMvcg/fy7qrFYbA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
