apiVersion: v1
kind: Secret
metadata:
    name: homepage-secret
    namespace: homepage
    labels:
        app.kubernetes.io/name: homepage
type: Opaque
stringData:
    HOMEPAGE_VAR_JELLYFIN_API_KEY: ENC[AES256_GCM,data:CMovQdkusPls6FoVsgNO6Nrzl6iDv1N5ZmJ8/e3zWQw=,iv:UYyz95J9DAdxszfFWtSEgnQVO+daCq4ICr0c9dhOiDQ=,tag:TxpsorwZoipqbkk4xk+cKA==,type:str]
    HOMEPAGE_VAR_SEERR_API_KEY: ENC[AES256_GCM,data:H6W6IFLwrPJe+c/3ZPm8oIPYvlpgFBBshviTo1TB3J6oWC8XhJws+nWqwK70AHMGiGQLsIaRfYg/E9Q1XkAzb929S6g=,iv:5xbd2kQQySOpW5ua89hH5KayxpOW3cuyTCsX9KOSpEk=,tag:XYb8PgiA6YjoUpSSG4o/gQ==,type:str]
    HOMEPAGE_VAR_SONARR_API_KEY: ENC[AES256_GCM,data:htOuweTWpi1GxJD+H8agTXXLFX6ymiEKIe0d6FsHwwI=,iv:JQtVirRf15QDtIScu9gaJCtTo3qcFtu0qAUoBF181Tk=,tag:Yt3Dt7hRdL9iuJ/nSAzm9w==,type:str]
    HOMEPAGE_VAR_RADARR_API_KEY: ENC[AES256_GCM,data:6Ndpao1Ncwg5+ACzyJezMBmx5r6sPOJO/4LV/uRvcms=,iv:PVJjgkBgy4lduheiJ40JrYbB+eQl8ONnHgo6wsfztro=,tag:z7Qsyf+yRZ0f8tVUl5qs/g==,type:str]
    HOMEPAGE_VAR_LIDARR_API_KEY: ENC[AES256_GCM,data:PljzYiCJscuQRUCWIv4E0qppOlgCJXRqV5cqJO2jUkU=,iv:S8gZctpT/+V1y+PV+CtcyrG5EO1/y4pf5PBEOTqwNA0=,tag:FBi2yUtiaiK1yjb4Fm4o+w==,type:str]
    HOMEPAGE_VAR_BAZARR_API_KEY: ENC[AES256_GCM,data:eucSifOuH6LfMC+zG3HkvsOn8Hc7MJRSozf2+Kbcpxs=,iv:bb7WpQBiWSu4Jq3F/bP4SEcJP6TC2EHEdrJft9GtEEU=,tag:89qU17p+MyQ3/Hptjw8wvA==,type:str]
    HOMEPAGE_VAR_PROWLARR_API_KEY: ENC[AES256_GCM,data:hepGLd2scNGq21sSIxXWwT9VBQPtfqt3e1b57NeN45Y=,iv:oA0Bqgtr0J0kTLStd/b7zWuFO8NnEapDMxInzG2AGtQ=,tag:yiB9O8LwF0UcPZaYcs5kCg==,type:str]
    HOMEPAGE_VAR_SABNZBD_API_KEY: ENC[AES256_GCM,data:XI/mTRc2sL/oIrUg49HzTh3MJAI7c1+iWpzr6Fv087M=,iv:TmLSPEyvrHsawdTGcNCaGM4RnPwyKin9JpPqSJU6fl8=,tag:8AYBtQjYJ/GwU722FiDuXQ==,type:str]
    HOMEPAGE_VAR_HA_TOKEN: ENC[AES256_GCM,data:0sBbBjCC8q7q8GwLgbtpCHBCpaq9lfJPdXp13Of2Pu9W+IstScTwOQC4OkoMfEqXY4FcHufDLZWGaUjVLTk+KObUPJV78Zxp89zqmKASRYHWDEuK7z8fr7s7bKAxkDhocuyia/yEMKdDul0wvzpuyRqub+ZNoK5EHZtdT0SSiIPoYcOXHAR/1YSz2kg0hVzeBIDt7grdA32IsU3raSJS0yHMZABIAkzX8gizRpaDc6kUHUGGo15q,iv:3vxYxWU6t0VOCtJRgzO882XqM9HYwkUwBw3NhjZ48RI=,tag:BMv2Ur+bByinJUcUBCEHKA==,type:str]
    HOMEPAGE_VAR_UNIFI_USERNAME: ENC[AES256_GCM,data:D1opn6M=,iv:/f/ggxvhfmMKW8JXPx+YTW/2BkcqcO+DLo5RN/fqiCU=,tag:UDUwdX61MUGI5IUR7yMobA==,type:str]
    HOMEPAGE_VAR_UNIFI_PASSWORD: ENC[AES256_GCM,data:9pXMMu7xnF2YI+L+Lx8W04QCQd24fqaj,iv:NGiEAuAIBpGmEIcJvv8NxIyKx4lkfWaR/voRbtXkbHk=,tag:1dIiSimImG5TTNkI+1CwAg==,type:str]
    HOMEPAGE_VAR_ADGUARD_USERNAME: ENC[AES256_GCM,data:HnU7UrI=,iv:1dPnO/A9EURwd86XzSqeKL6PQNxwtHnOLnddM/FXKIg=,tag:SrIUUS6n1sHN931EHpn8Xw==,type:str]
    HOMEPAGE_VAR_ADGUARD_PASSWORD: ENC[AES256_GCM,data:suQWn/qZ+KTQuSDKZJvd1DiRgW4=,iv:bBy/TWYf3jihmORBLlnFIW1N2X46QaASO6VUQIof9tY=,tag:awGFAv9Vmdt+VveFXyYoeQ==,type:str]
    HOMEPAGE_VAR_QNAP_USERNAME: ENC[AES256_GCM,data:PjIdavCDyBdkiKLr5Lg=,iv:GbPxz/gamPmz/8BgXrkgs3lBvhfMWCLWNFQPlA+Ggbo=,tag:XLGvHvzPouANjfNcJX6gTw==,type:str]
    HOMEPAGE_VAR_QNAP_PASSWORD: ENC[AES256_GCM,data:Rv4OQMHZL0OyFNcdSQjUSi7kZJHEbpu5,iv:jgwADWSUbTTg6UULk3n9PRSecwuQ7IMOFLGLip0vF9c=,tag:O8DbPTgSmYiUG1cVSjlVXg==,type:str]
    HOMEPAGE_VAR_GRAFANA_USERNAME: ENC[AES256_GCM,data:WfJ6ACs=,iv:/vT7+ti7i7h1iz8fWqZdSJGTxUUHP6JV+T72Y6yDIDQ=,tag:mnuIreO/VnSndszUtbAgvw==,type:str]
    HOMEPAGE_VAR_GRAFANA_PASSWORD: ENC[AES256_GCM,data:RE/lxRcTehxNx4LtbhdBi3u6FYTqqsMrSLQZL8sdIgc=,iv:90St8Lz6qsqPCtiahl9joTg67DtYC0PAnaWbP6OxNuw=,tag:NQXuj3xGBgPf3BGUYTdf9Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1VC9FYTl1aThGS08yM1dL
            ZTk4QStzRlZmSVpORnczWmxveXJVN1ZmZUh3CkxjSi9kc3NIRkVoZmlnRVJqRW4r
            dmVWc0kyNWhxR1U0ZW43VUFuMFRWR1UKLS0tIHFyVkZkeCtBWXFQYjFqbnBEK2JE
            eVhKOUhlQUUvalVDVVo3R1FwV2NUc2cKAWiWAHzMSOpFRfo8Xm8gmNc4na1mVnPj
            sLVmKpFWOc87oq0O2d9suhBzTWk5L+TIdEQy9oEYXjxkSuG0UitYmA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1j6zlq24dlzd9as6gq835980ahzelmnuu7d8ydkz54t28kzhv0csse96epz
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-27T03:36:46Z"
    mac: ENC[AES256_GCM,data:wwN0ZDAFrmxi2gyjXBy3S56jGz/sn85UgbgKj4XM+3DPHZWneqXmwNnlwr8wCHTMcouIaRKyaVWqsiJaOKpBQyWN5tIbK/ISJVMKFKC7pgePYg/CPd9oA5ZaX29fVqSZIRphiAuESGQshsjNPDqcpJc/7zw2JNZnlNzCzy//9xo=,iv:7Lj+JFKmgPFZkJW+l3fQLBWGCHUbBvXUWC6fXKt2lpc=,tag:XxqfYYd4BYoN0gNkiKTZkQ==,type:str]
    version: 3.13.2
