apiVersion: v1
kind: Secret
metadata:
    name: gatus-ntfy
    namespace: observability
type: Opaque
stringData:
    NTFY_TOKEN: ENC[AES256_GCM,data:aVhm8uuvFxGROY8Qt0bEIQMehCa6y6b5st24ts5yl+k=,iv:HJdlQCR6fGfmQZqLyKUHy3eHQVHvs/qGckcdKuUPkKE=,tag:NWRlMWkZXPrn3XhtSAfHhw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFcTRCRmY5ejFmb2VWMkNL
            RkNoMVFHRmc3WHBqNnVvNi9aam84anQ0RTFZClRHd1ZRV0pHOU11UTJBVFhKTWNM
            b1N6QVdIOUNSTnI5N08vb2hmczlwc2sKLS0tIEJiNmlJRllOSU93eGRlWmd2WUVK
            WkVvVTlmUy9NWmw5OGU0dHhIVFYzQ0EKBJOfCKxwJTkVEptzw3UYIWIbz0Nd38UD
            Uud9hwnH0HHZNdURetNDOTPQhjn5JZO4VG8XzX8OisWVtEQKMzZdgw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1j6zlq24dlzd9as6gq835980ahzelmnuu7d8ydkz54t28kzhv0csse96epz
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-27T14:03:40Z"
    mac: ENC[AES256_GCM,data:eOUMitGsSBVDbnpXVNUKYAG8gQSmmqgdlUuPmS9vnATa98K75zOhG6DDfvBreECthFiZ9Lap1b6GmkXqWePY3xikvLV01XOtFr+DO0J0YRedw3grNLJIqWaR3/csDoDfIHEtZsP1NyV2VJP+5v2K+iMmJsfK7Km3RB0Rbg39SKo=,iv:UlB3kHUH43gIDblaxqtmR5KU/f546M/D2JLG0AFcnks=,tag:bgfuSEo0O39U1VnQveUqCw==,type:str]
    version: 3.13.2
