apiVersion: v1
kind: Secret
metadata:
    name: gatus-values
    namespace: observability
type: Opaque
data:
    values.yaml: ENC[AES256_GCM,data:BzHcbP9NDOuzz49qI47PKAorwnRgU0pyiLmbhyItxWxmGRCf+/6g+jeWqBLAQLXyR2Q9CYBbhgxFxTUFBeizGA5Uxd7YNjRooUaq40ASAJw=,iv:tV5Na9fMHta5YvP6crCLUvZOCNqxTMm3dDdskSoEa8A=,tag:fEdh6W2MNIgWzIPaA3BDTg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0WEdZUXFBQW8vcDBlR2d4
            MXpOaXo1bzdNemQ0UjBmMFduaFlqN3R6R1dJCkxaZDRyMm05bkFjcXNRNHpydm1I
            K0hESHdQS2lsam5BdzhseDZqNHVGZFUKLS0tIGYzZWVVaUJzS2VJQzZsT0RKYWp2
            dWxDN3hoakxlVE1Pb29wU1FCZTFuNkEKq0msXqc9jl3nNEayztCLggeeZzhnyE5z
            tJEVITc/TFIZv7LAuxX+Q2Gxezi/E0g85tzwXVsYN5qvamt4VmW2Xg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1j6zlq24dlzd9as6gq835980ahzelmnuu7d8ydkz54t28kzhv0csse96epz
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-27T14:20:36Z"
    mac: ENC[AES256_GCM,data:9khCm2Wgl4idQ3siQLzyDvHWWPROmUVP+XF/pMCMRoOoBAr3UV7AveUhbDsCgur1yrQ+QoaEtsI0UpcO8ZBiyC1U0E3t1EQPACzm1Ik+3TB2vLGWcJGE/2mCLR1MiDmRz9Cq9XFyUTCybOvEzUcTlGNhTGh4ejbTgUlAq+r4XmA=,iv:ndcJse6uIfzBS19yxXTwDK4BuEru7xVkqOAByoiATTs=,tag:0rFatmImpJUP1VvTHlfutQ==,type:str]
    version: 3.13.2
