apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token-secret
    namespace: cert-manager
stringData:
    api-token: ENC[AES256_GCM,data:z8lDa02e36wgUR/5L4UJOrYdwY/to595/93hCFn4FPiONR/svAvQ9Q==,iv:lwzOpZJMaZNfyQu50WlMz7jjKNNEiWWtmw3mHdI4GVM=,tag:+A4OASHpIHLFIHYCFabOIw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEL1NIdmZtK0RzR0Q1WWVt
            bnBtYWNPYWdQQVBJcEtCelZlUVlnR1JlRXh3CkMwanZOZCtGNi9vZGtNb2JGSHNY
            Yko1TjNZSkhmeUM3bVZJRlh6MGhpRFUKLS0tIEpLTEoxenhDT2dGa3hneGUzTzhO
            aTA2dGwwVG5Xbit3YkdMRXE3Mk42LzgK/qxSpEZIdEw71uzBvVanrg07KI8HHLrW
            g/pGMyr4io3g6eub227d3zG17v8RKMVKPjYwIY8MVABFSQLoEojtEg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1j6zlq24dlzd9as6gq835980ahzelmnuu7d8ydkz54t28kzhv0csse96epz
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-17T13:21:38Z"
    mac: ENC[AES256_GCM,data:EGDGTm2tG9LGOYFtyS/l/eCZxqecL5hMCqDNto/wgxeqGcOffkMHmsjU3rpVRcpstjV0v/mhL/ThmXbqRFN4MIhUiI4yOQYn1ZRCBB147ptYYFOf+A1hrj6u6KF5AlKSDPNjhFmahz8/5gKz41Y1eshcb5Q215Me9RNp7rRFPFY=,iv:MdSqoMLAtFN+XqcJ74Yt41N3KLIo4X3/gSgfZZixG2E=,tag:NRivGaRwcylKaiROgA0HyA==,type:str]
    version: 3.13.2
