apiVersion: ENC[AES256_GCM,data:ZFI=,iv:NScT5OOrL8Kii4IUcUi3h5BD01v5F/zuyu7WyXKV1oA=,tag:kJ9Jkt9+MWD2C93RICYIbw==,type:str]
kind: ENC[AES256_GCM,data:QSVQ+ani,iv:N3oDcy2ADSjb3zXrC65HpPCQ9dK//tEK0pahlXxKsrY=,tag:O1G2oDyhxiZ2+QJEC5/m4w==,type:str]
metadata:
    name: ENC[AES256_GCM,data:yvWC6/s06ObC9aQ=,iv:MWphVQ/tAx93qud4fY0yzJEE5ohZGvLsXAKDW8HjX8o=,tag:8ppthnuf17Sm3ldkE+QhmQ==,type:str]
    namespace: ENC[AES256_GCM,data:TRHCXg==,iv:TaaUlYVjplAJrIOJSiozwvyEAFcRKvN0kGQzJpJxcTI=,tag:fk7eEDrnbX3tmDueWp/AlQ==,type:str]
type: ENC[AES256_GCM,data:CV3fiaDF,iv:MJv5wZbgLAaXZBfn4uEYGSXabIBOh9JgWqqjMTo7y8E=,tag:1cAO0fSGkeWqBHzT0KFECg==,type:str]
stringData:
    #ENC[AES256_GCM,data:kFddvhqeIUDsVRQxZEfnldzafo4fJsSM7+EQnkJ5pkJ1SzYm4x/hAxgG9QGjVtON8VXZHIMMNBH7teR1TMdnQg==,iv:qqk2Z0B6y0gX7fts+iGo0KsDpGEGaZYJIN0RbtDDI3I=,tag:GqqJDga3DmrchXb8xBP9vw==,type:comment]
    #ENC[AES256_GCM,data:dV/1yrykzRgjtuVC1natQMdKx4h14YCtl635nE9yu4Juyys0IfSoaayn6Sy74ZmPigKBZ4qBUsfx2hC7/WQTyRWneaE9FQ==,iv:PCzwYBoBE9k9kqtunkeMPoh0x3bkq/Ay/k5ae6EZKvQ=,tag:g5pjMQf/tPH4vaOSo9OV+w==,type:comment]
    #ENC[AES256_GCM,data:YAW0tzxGyalRG2GdPigcsFz0hiU/JQBRTd4YPXsgUVg=,iv:8alxYv5sQFaaNUQeIoeS6EgRxBSQzkaX0Ijzfziqhqg=,tag:1FcGw9esR8tvDdvG/liLIg==,type:comment]
    WHATSAPP_API_KEY: ENC[AES256_GCM,data:HpOssIq5uda2+9XjtmowVCvI9RAB0FmA,iv:atszM9E9LVJbn8QKKE7R2+04dlZMMza1Nzj3+z1+adg=,tag:6Mqbh43+c/hbYDGbBcQb9A==,type:str]
    WAHA_DASHBOARD_PASSWORD: ENC[AES256_GCM,data:flJ2loBqKmr17BTcrY0=,iv:FASDBTc4NpLA/S9+n3J+uTt8SFZwcLWcTmpYm7ElYnQ=,tag:nsu8jJJjN/gTRmUVBkETjg==,type:str]
    WHATSAPP_SWAGGER_PASSWORD: ENC[AES256_GCM,data:Bxm5mJQNtuXce0Yt0J4=,iv:zMf98f1nQOm1atFPAk5wTTVAMoEdaHydk7R+LCr5K/0=,tag:cckuAKBohhITIXT8TL7V7A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByZGx5eXZuYnhUdEE2RVU2
            cmRPVlVIaGlXdkVxZE5uY2hVU3JOK2tEWTFjCnMrSTFXbHFYeGxwR3QvY2Q4MXZM
            b3pPaXlMb1lIY09kSHFmN1hHSkd0WlEKLS0tIGV1TEh4T1ZjVWtkUTdkY0JCazNE
            ZlZKSEdqcFBUSlJnSUN1VmlzU3A5NXMKrZrE7aTGgpjmLFWtA7kaYsuRMLU0hitc
            lvisuvJNrnabAMAmbdZ6rz/S7kM5S5Kkvhd4YJiKihOinyHvvQshaw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1j6zlq24dlzd9as6gq835980ahzelmnuu7d8ydkz54t28kzhv0csse96epz
    lastmodified: "2026-07-22T22:03:09Z"
    mac: ENC[AES256_GCM,data:76H10L76v1N1B/vwyglaF4JYTFSKioIXMJmNXHIYNEhN4hwaUR919jgve5AYVuhI0wVKD1YZ6ZeWdYd1oLKl/qYiWBc4bUByOakTGmSeR2qveID29BXzcjCXFEXzYsH9dI7sGvY+WD+wrsVxyMCWBCB2QxPMFDxi006jti6Tq2c=,iv:dOhiL+zP/AQyTGhp4NHpU7+kA+4s6qm/00IeThM8maA=,tag:qUsis2uiGNQ5QfcmwZY1SQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
