apiVersion: ENC[AES256_GCM,data:zk0=,iv:j9N6NxTRPrWFjovOhsZnsiggt3SeGsxNwMLqJVvyCoE=,tag:cZ08BQABPF+8OaMsRk4Kgw==,type:str]
kind: ENC[AES256_GCM,data:ytgB7psY,iv:01V1PF2tGuJ/NNUZP1OogWnDT3jJwO8rqFmYy3bqU+A=,tag:vdVnmWTjZ8kTbqiRRbGhUw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:0CLq+moBXs1PDrU=,iv:4bkH2F2N+PsGqxXLABU3imF/QtYLhQpjH9TqiHmma/Y=,tag:7iDYQl/Jj254pNOtMc54tQ==,type:str]
    namespace: ENC[AES256_GCM,data:+Rbl/Q==,iv:kodK2iKwLjkyv/+6YgvgwX8DQyaVHsnQ4XFInPZFgF4=,tag:1KvJ8JqXZZjQEK2umtx+rQ==,type:str]
type: ENC[AES256_GCM,data:7wguWDPv,iv:5Khid126Hb//fvB4h2SvMZGtpWKfYc7Ia8e/CAS1T9k=,tag:JOTDq36hFm8J4+Qpepk6nA==,type:str]
stringData:
    #ENC[AES256_GCM,data:+Ds8tWT4BwvrWgI2FU+YH6k8czfz0TEaca6HWroFHsgHMf2JXo8TKPcB2DgkYZTpC+a148gNBUT9Ui228ymxVBQ=,iv:JOmhzQCfsrMSHET9LMBUT736GFqKI62a9PYC8tiuktQ=,tag:QtvWysIVfvGiTHFGaONyqw==,type:comment]
    #ENC[AES256_GCM,data:ThgkXQFMS012VyGqVP/q4/HeB91ylu2uNVVZQC1934MpXY8AAw8ejE2NBhy3cWUQIuAy4zAHvoYPDxKG9OyN04pJZ7l+Uw==,iv:uMkRCsDCND6I5oivlhGCh68Uu+vhGG02cy4Qw4UXivE=,tag:J7jctGH8ztRzVizoUD0cMA==,type:comment]
    #ENC[AES256_GCM,data:e7F+Kx/mu9YrJbwgJ6/DdboyiXCFwicoQyccpY5D8p0cjCgEaDdVIGCBx+vvRENaWZGQ6DdTBMn0EQCjc7E7DaPLijXKXw==,iv:KkyjQ+z8PCUNsqLeco/cCJ61+ZwqSvq2agv0DNVeNdE=,tag:2/HkIPO+fT+9eMYEnn0TGA==,type:comment]
    #ENC[AES256_GCM,data:2lLpmdkFPo2UffkRypFeypcoZqVH0w1VuRmZGvdndA==,iv:98fOY5fhlx2vgBDXDK4wRzewATMq598TGrr0Q5XAXvM=,tag:bgtjPywRXM++l9vxZrul4g==,type:comment]
    WHATSAPP_API_KEY: ENC[AES256_GCM,data:8UGabSzNUKon5lzOJS6XHP95SID6DIUp,iv:tzcsyfY/gUPUT78n1k5XUTcIjTJkwrH77OJcbQaieLo=,tag:uscbw/9tlEsroWwmBCtGRg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVVVFhd3FWekFONUx4TUt3
            SWVVSVROa0ZpQXZTMU9jWDcycGxtRWl6Nm0wCkxnaTBBRFcvVWFJMUphMFNYVEc4
            Q0ljcjV5cENvS3ZwNHdWZjc2N0tSeHcKLS0tIFVwTGNzU01SdUt4TnFUVWpMOGRL
            UWRnOEUvVjI3bHhITnkrTkx4TVlMd0EKT5fcEhhMuVvbqarjfNCHgIRjNeVl675u
            mMSiKQ1801zs5iHGp1ef8Rv4kxwHMDaOSsptIwp9LraD0dASc3dtFw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1j6zlq24dlzd9as6gq835980ahzelmnuu7d8ydkz54t28kzhv0csse96epz
    lastmodified: "2026-07-22T22:46:54Z"
    mac: ENC[AES256_GCM,data:VDyPNsUkUvZD9/xgrErn6Acsq4ozFekF3llNAn9mo+le/HIZ+VMKHlVwkKafGUTMN3WYQt4+uShCSXXhh0Xu/hAHHFMPHeyUEKEstpuFwnSkP+g0VvB9uur1OPf84wgBHLO76KCpo8+LsYYVU5PTZdBOLStVN2UbJRjOYHb8VvY=,iv:pMsHLanLJDbgp03J2g02rsAfXMscFW0GAM6IiM74l+s=,tag:w6HxMb7ONp0XwfVXq8CYzQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
