apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-ntfy
    namespace: observability
stringData:
    token: ENC[AES256_GCM,data:hih93DZqOvseACfeQN+6jIcwYWQyC9/fj+1Gw7Ux8Fk=,iv:hfM0Ne6VhAE+eR9JL+0yogq9kMhvXtw8sxMb+SRlU7M=,tag:FP950+EVdsDx035sDtkBNg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvTEgwTldwUXB6TjRJNVA2
            aXRqQVpzNTNtd1ZObStMSnZpbG9PV044czJVCjhNYkZXQXJhUGdHbnMyM3g0VzZy
            aUszdDJWRDB2c2dEQzNsb3Z1am5vdTAKLS0tIFF4K2oycmJnM3JNOGRBOWRiK21a
            RU93U0Qzb0ExN05ZYXBLbHhlcXVtNVkKxEBqeqJMfAUJV578w9jsSltgiG11QaiY
            pe1IqtSzBLsflMmrhDOOv0BF09fQ8kkm8aUKt7w0kcqZZ4YUpVb0DQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1j6zlq24dlzd9as6gq835980ahzelmnuu7d8ydkz54t28kzhv0csse96epz
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-07T21:49:37Z"
    mac: ENC[AES256_GCM,data:wASqq8XhT12jidgH0caAQ7XvrJAj+FK96inY2FKx7s8Z7OqcjxLrYu4ALmtVikeVSa4Sx6Esvrbw+L7inMDLE+BMMjRKcXjK/U2llzVLr7MGsC7SfLcmIOcJuPzD16G5QPDXbRjYRoLfvaa0TvNzD1j/ymrOocfzdODjGc+XwPI=,iv:0N+Q97jACCqWTTuCP69U+GReSAenwBKR8TLw6wlGvWE=,tag:7DH8KJWaM2D0QLKpeuPOJA==,type:str]
    version: 3.13.2
