apiVersion: ENC[AES256_GCM,data:+5Y=,iv:st8Nkrfg2pxnx1kUmHv2WjzozKYIxdDqoPP/H4qlEfM=,tag:xkBIlE7ICM3BbpEKmGoZpQ==,type:str]
kind: ENC[AES256_GCM,data:GxS1LHIE,iv:rfDh31AckzQyEmKalSmLvwPTAqNJd9I8KEeWIkHzgtw=,tag:AeFIW8wq5YDgMQZiHGsv/A==,type:str]
metadata:
    name: ENC[AES256_GCM,data:CsVAF9MUt4Cp9LL1Cw==,iv:yluBUhZkDsBN75vcL9Ikk5Z8LcfoJ5FIhKuV25W664Y=,tag:C/r/blq5O3n2CShXEBl/yg==,type:str]
    namespace: ENC[AES256_GCM,data:wW9XwBrGpTe/j32mvA==,iv:ma9BxPa7W21y9F7S+DLS+KFIjOHKdEMhY+0KdU5jFK4=,tag:8zhzfjOkZ80NJyw/DqyVVw==,type:str]
type: ENC[AES256_GCM,data:nLlg20E5,iv:V6BOUeucyXuw9RHxBg81YrJImZri1dZKJi1MiYFfsBg=,tag:HHRRt3KS73bowDZBXICeDw==,type:str]
stringData:
    admin-user: ENC[AES256_GCM,data:iFBkg5U=,iv:gXOWHkD+ERGirdFDJdbZgUBBmoH140Z0IIxpjbFWvqw=,tag:lZPbyefwPhSbfjRoFRj5Yg==,type:str]
    admin-password: ENC[AES256_GCM,data:bi3NxeiHrA9nX/czoFniGfeXIZhrFouywG1J8yS2tcE=,iv:OkEKxv8ozO67pbGcoWKNUW6gLH/9dXlAzkdHbw+cG3E=,tag:7uIRZCuFps5hVeSpCsECMQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5bjhmMElDSE9wbDZDenhn
            WjRZdXBDNGZOZ2hianIwdG5hU0NZUHJva0dNCmxIV1VxVmdjOWlLMU8vN28rdktB
            VStlY1BTcTBTU2xWUjE3RlRMNVczaUEKLS0tIFpCRE12NXUzeC9LbWdhWDJlWjV6
            VFVEemNWWE9CTFRNMnk1YzJLVG9iS3MKjaVpEf0BCnkO8Usynbtx/D8wxLoXGElj
            OsEJch7ydIIfprkOrZc/dkgqK5tDPIUUFBFNsdI9vOXp9ljKDa+rOQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1j6zlq24dlzd9as6gq835980ahzelmnuu7d8ydkz54t28kzhv0csse96epz
    lastmodified: "2026-07-22T02:08:12Z"
    mac: ENC[AES256_GCM,data:i806nf9f7Q9cKzKa0p8gbu7k6NbllkbgydHPRBNU4yrBsRYVC45i78pSnlKggxcg2496zsd3RihjEh+PzcXbz6WKC7mOKPmt4JNV/4Ed0qOLOqQGW59SrGEifKixQ+erm5fXl5SWPrhaVRzwTE0xXW73Dbd8Ak4yCpgaBmWuH+M=,iv:dO0gwMojDGsH03OJr/YfvRwz3WlQSSqKKkAKc84CC2s=,tag:Z0WLcdzNk20dSsJcZQvkBQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
